//AHSRC:base/dyc_api.c
BGBDY_API int dycObjectP(dyt obj);
BGBDY_API int dycClassP(dyt obj);
BGBDY_API int dycSlotP(dyt obj);
BGBDY_API int dycMethodP(dyt obj);
BGBDY_API int dycObjectInstanceOfP(dyt obj, char *name);
BGBDY_API void dycRegisterClassResolver(dycClass (*fn)(char *name));
BGBDY_API dycClass dycBeginClass(char *name, char *super);
BGBDY_API dycClass dycEndClass();
BGBDY_API void dycBeginClassAnon(dycClass super);
BGBDY_API dycClass dycEndClassAnon();
BGBDY_API void dycClassSuper(char *name);
BGBDY_API void dycAddClassFlags(s64 flags);
BGBDY_API void dycSlotBasic(char *name, char *sig);
BGBDY_API void dycSlotStatic(char *name, char *sig);
BGBDY_API void dycSlotInit(char *name, char *sig);
BGBDY_API void dycSlotStatici(char *name, char *sig, int val);
BGBDY_API void dycSlotStaticl(char *name, char *sig, s64 val);
BGBDY_API void dycSlotStaticf(char *name, char *sig, double val);
BGBDY_API void dycSlotStaticd(char *name, char *sig, double val);
BGBDY_API void dycSlotStaticU(char *name, char *sig, void *val);
BGBDY_API void dycSlotStaticr(char *name, char *sig, dyt val);
BGBDY_API void dycSlotIniti(char *name, char *sig, int val);
BGBDY_API void dycSlotInitl(char *name, char *sig, s64 val);
BGBDY_API void dycSlotInitf(char *name, char *sig, double val);
BGBDY_API void dycSlotInitd(char *name, char *sig, double val);
BGBDY_API void dycSlotInitU(char *name, char *sig, void *val);
BGBDY_API void dycSlotInitr(char *name, char *sig, dyt val);
BGBDY_API void dycSlotDelegate(char *name, char *cname);
BGBDY_API void dycSlotStaticDelegate(char *name, char *cname);
BGBDY_API void dycSlotInitDelegater(char *name, char *sig, dyt val);
BGBDY_API void dycSlotStaticDelegater(char *name, char *sig, dyt val);
BGBDY_API void dycMethodBasic(char *name, char *sig);
BGBDY_API void dycMethodStatic(char *name, char *sig);
BGBDY_API void dycMethodFunc(char *name, char *sig, dyt fcn);
BGBDY_API void dycMethodStaticFunc(char *name, char *sig, dyt fcn);
BGBDY_API void dycMethodCFunc(char *name, char *sig, void *fcn);
BGBDY_API void dycMethodCFuncData(char *name, char *sig, void *fcn, void *data);
BGBDY_API void dycMethodCSelf(char *name, char *sig, void *fcn);
BGBDY_API void dycMethodCSelfData(char *name, char *sig, void *fcn, void *data);
BGBDY_API void dycMethodStaticCFunc(char *name, char *sig, void *fcn);
BGBDY_API void dycMethodStaticCFuncData(char *name, char *sig, void *fcn, void *data);
BGBDY_API void dycMethodStaticCSelf(char *name, char *sig, void *fcn);
BGBDY_API void dycMethodStaticCSelfData(char *name, char *sig, void *fcn, void *data);
BGBDY_API void dycSlotMethod(char *name, char *sig);
BGBDY_API void dycStaticSlotMethod(char *name, char *sig);
BGBDY_API void dycAddMethodFlags(char *name, char *sig, s64 flags);
BGBDY_API void dycAddMethodAccess(char *name, char *sig, dyAccessMode acc);
BGBDY_API void dycAddSlotFlags(char *name, s64 flags);
BGBDY_API void dycAddSlotAccess(char *name, dyAccessMode acc);
BGBDY_API void dycClassInterface(char *name);
BGBDY_API dycClass dycBeginIface(char *name, char *super);
BGBDY_API dycClass dycEndIface();
BGBDY_API void dycIfaceSuper(char *name);
BGBDY_API void dycIfaceMethod(char *name, char *sig);
BGBDY_API void dycIfaceSlot(char *name, char *sig);
BGBDY_API dycClass dycBeginStruct(char *name);
BGBDY_API dycClass dycEndStruct();
BGBDY_API dycClass dycLookupClass(char *name);
BGBDY_API dycClass dycGetClass(char *name);
BGBDY_API dycObject dycAlloc(dycClass inf);
BGBDY_API void dycFreeObject(dycObject obj);
BGBDY_API void dycDeleteObject(dycObject obj);
BGBDY_API void dycSetObjectObject(dycObject dst, dycObject src);
BGBDY_API int dycSubclassP(dycClass info, dycClass super);
BGBDY_API int dycInstanceP(dycObject obj, dycClass inf);
BGBDY_API int dycClassDynamicP(dycClass info);
BGBDY_API int dycObjectDynamicP(dycObject obj);
BGBDY_API dycClass dycGetObjClass(dycObject obj);
BGBDY_API dycClass dycGetClassSuper(dycClass inf);
BGBDY_API char *dycGetClassName(dycClass inf);
BGBDY_API char *dycGetObjClassName(dycObject obj);
BGBDY_API s64 dycGetClassFlags(dycClass inf);
BGBDY_API char *dycGetClassShortName(dycClass inf);
BGBDY_API char *dycGetClassSpecialName(dycClass inf, char *name);
BGBDY_API char *dycGetObjClassShortName(dycObject obj);
BGBDY_API dycClassV dycGetClassVersion(dycClass inf);
BGBDY_API int dycGetStructSize(dycClassV vinf);
BGBDY_API dycClass dycGetVersionClass(dycClassV vinf);
BGBDY_API int dycGetStructSlotOffset(dycClassV vinf, dycSlot idx);
BGBDY_API char *dycGetSlotName(dycSlot idx);
BGBDY_API char *dycGetSlotSig(dycSlot idx);
BGBDY_API dycClass dycGetSlotClass(dycSlot idx);
BGBDY_API s64 dycGetSlotFlags(dycSlot idx);
BGBDY_API char *dycGetMethodName(dycMethod idx);
BGBDY_API char *dycGetMethodSig(dycMethod idx);
BGBDY_API dycClass dycGetMethodClass(dycMethod idx);
BGBDY_API s64 dycGetMethodFlags(dycMethod idx);
BGBDY_API dycSlot dycIdxSlot(dycClass info, char *name);
BGBDY_API dycSlot dycIdxObjSlot(dycObject obj, char *name);
BGBDY_API dycMethod dycIdxMethod(dycClass inf, char *name, char *sig);
BGBDY_API dycMethod dycIdxObjMethod(dycObject obj, char *name, char *sig);
BGBDY_API void *dycGetSlotPtr(dycObject obj, dycSlot idx);
BGBDY_API void *dycGetInitPtr(dycClass inf, dycSlot idx);
BGBDY_API void *dycGetStaticPtr(dycClass inf, dycSlot idx);
BGBDY_API void *dycGetStructPtr(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API void *dycPtrSlot(dycObject obj, char *name);
BGBDY_API void *dycPtrStaticSlot(dycClass info, char *name);
BGBDY_API void *dycPtrInitSlot(dycClass info, char *name);
BGBDY_API void *dycPtrStructSlot(dycClassV vinf, void *obj, char *name);
BGBDY_API int dycInstanceOfP(dycObject obj, char *name);
BGBDY_API int dycSubclassOfP(char *name, char *super);
BGBDY_API dyt dycLookupMethodSig(dycObject obj, char *name, char *sig);
BGBDY_API dyt dycLookupStaticMethodSig(dycClass inf, char *name, char *sig);
BGBDY_API dyt dycGetMethodFunc(dycClass inf, dycMethod idx);
BGBDY_API dyt dycGetObjMethodFunc(dycObject obj, dycMethod idx);
BGBDY_API void dycSetMethodFunc(dycClass inf, dycMethod idx, dyt fcn);
BGBDY_API void dycSetObjMethodFunc(dycObject obj, dycMethod idx, dyt fcn);
BGBDY_API dycSlot dycAddObjSlot(dycObject obj, char *name, char *sig);
BGBDY_API dycMethod dycAddObjMethod(dycObject obj, char *name, char *sig);
BGBDY_API dycObject dycCloneObject(dycObject obj);
BGBDY_API dycObject dycCopyObject(dycObject obj);
BGBDY_API dycObject dycGetObjDelegate(dycObject obj, char *name);
BGBDY_API void dycSetObjDelegate(dycObject obj, char *name, dycObject obj1);
BGBDY_API dycSlot *dycEnumSlotArray(dycClass inf);
BGBDY_API dycMethod *dycEnumMethodArray(dycClass inf);
BGBDY_API dycSlot *dycEnumDelegateSlotArray(dycClass inf);
BGBDY_API dycSlot *dycEnumClassSlotArray(char *name);
BGBDY_API dycMethod *dycEnumClassMethodArray(char *name);
BGBDY_API dycSlot *dycEnumClassDelegateSlotArray(char *name);
BGBDY_API dycObject dycAllocClass(char *name);
BGBDY_API void *dycPtrClassSlot(char *cname, char *sname);
BGBDY_API dycSlot dycIdxClassSlot(char *cname, char *sname);
BGBDY_API dycMethod dycIdxClassMethod(char *cname, char *name, char *sig);
BGBDY_API dyt dycGetSlot(dycObject obj, char *name);
BGBDY_API dyt dycGetSlotr(dycObject obj, char *name);
BGBDY_API void *dycGetSlotp(dycObject obj, char *name);
BGBDY_API int dycGetSlotsb(dycObject obj, char *name);
BGBDY_API int dycGetSlotub(dycObject obj, char *name);
BGBDY_API int dycGetSlotss(dycObject obj, char *name);
BGBDY_API int dycGetSlotus(dycObject obj, char *name);
BGBDY_API int dycGetSloti(dycObject obj, char *name);
BGBDY_API s64 dycGetSlotl(dycObject obj, char *name);
BGBDY_API float dycGetSlotf(dycObject obj, char *name);
BGBDY_API double dycGetSlotd(dycObject obj, char *name);
BGBDY_API int dycSetSlot(dycObject obj, char *name, dyt val);
BGBDY_API int dycSetSlotr(dycObject obj, char *name, dyt val);
BGBDY_API int dycSetSlotp(dycObject obj, char *name, void *val);
BGBDY_API int dycSetSlotsb(dycObject obj, char *name, int val);
BGBDY_API int dycSetSlotub(dycObject obj, char *name, int val);
BGBDY_API int dycSetSlotss(dycObject obj, char *name, int val);
BGBDY_API int dycSetSlotus(dycObject obj, char *name, int val);
BGBDY_API int dycSetSloti(dycObject obj, char *name, int val);
BGBDY_API int dycSetSlotl(dycObject obj, char *name, s64 val);
BGBDY_API int dycSetSlotf(dycObject obj, char *name, float val);
BGBDY_API int dycSetSlotd(dycObject obj, char *name, double val);
BGBDY_API dyt dycGet(dycObject obj, dycSlot idx);
BGBDY_API int dycSet(dycObject obj, dycSlot slot, dyt val);
BGBDY_API dyt dycGetr(dycObject obj, dycSlot idx);
BGBDY_API void dycSetr(dycObject obj, dycSlot idx, dyt val);
BGBDY_API int dycGetsb(dycObject obj, dycSlot idx);
BGBDY_API int dycGetub(dycObject obj, dycSlot idx);
BGBDY_API int dycGetss(dycObject obj, dycSlot idx);
BGBDY_API int dycGetus(dycObject obj, dycSlot idx);
BGBDY_API int dycGeti(dycObject obj, dycSlot idx);
BGBDY_API s64 dycGetl(dycObject obj, dycSlot idx);
BGBDY_API float dycGetf(dycObject obj, dycSlot idx);
BGBDY_API double dycGetd(dycObject obj, dycSlot idx);
BGBDY_API void *dycGetp(dycObject obj, dycSlot idx);
BGBDY_API void dycSetsb(dycObject obj, dycSlot idx, int val);
BGBDY_API void dycSetub(dycObject obj, dycSlot idx, int val);
BGBDY_API void dycSetss(dycObject obj, dycSlot idx, int val);
BGBDY_API void dycSetus(dycObject obj, dycSlot idx, int val);
BGBDY_API void dycSeti(dycObject obj, dycSlot idx, int val);
BGBDY_API void dycSetl(dycObject obj, dycSlot idx, s64 val);
BGBDY_API void dycSetf(dycObject obj, dycSlot idx, float val);
BGBDY_API void dycSetd(dycObject obj, dycSlot idx, double val);
BGBDY_API void dycSetp(dycObject obj, dycSlot idx, void *val);
BGBDY_API dyt dycGetStaticSlot(dycClass inf, char *name);
BGBDY_API int dycSetStaticSlot(dycClass inf, char *name, dyt val);
BGBDY_API int dycGetStaticsb(dycClass inf, dycSlot idx);
BGBDY_API int dycGetStaticub(dycClass inf, dycSlot idx);
BGBDY_API int dycGetStaticss(dycClass inf, dycSlot idx);
BGBDY_API int dycGetStaticus(dycClass inf, dycSlot idx);
BGBDY_API int dycGetStatici(dycClass inf, dycSlot idx);
BGBDY_API s64 dycGetStaticl(dycClass inf, dycSlot idx);
BGBDY_API float dycGetStaticf(dycClass inf, dycSlot idx);
BGBDY_API double dycGetStaticd(dycClass inf, dycSlot idx);
BGBDY_API dyt dycGetStaticr(dycClass inf, dycSlot idx);
BGBDY_API void *dycGetStaticp(dycClass inf, dycSlot idx);
BGBDY_API void dycSetStaticsb(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetStaticub(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetStaticss(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetStaticus(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetStatici(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetStaticl(dycClass inf, dycSlot idx, s64 val);
BGBDY_API void dycSetStaticf(dycClass inf, dycSlot idx, float val);
BGBDY_API void dycSetStaticd(dycClass inf, dycSlot idx, double val);
BGBDY_API void dycSetStaticr(dycClass inf, dycSlot idx, dyt val);
BGBDY_API void dycSetStaticp(dycClass inf, dycSlot idx, void *val);
BGBDY_API int dycGetInitsb(dycClass inf, dycSlot idx);
BGBDY_API int dycGetInitub(dycClass inf, dycSlot idx);
BGBDY_API int dycGetInitss(dycClass inf, dycSlot idx);
BGBDY_API int dycGetInitus(dycClass inf, dycSlot idx);
BGBDY_API int dycGetIniti(dycClass inf, dycSlot idx);
BGBDY_API s64 dycGetInitl(dycClass inf, dycSlot idx);
BGBDY_API float dycGetInitf(dycClass inf, dycSlot idx);
BGBDY_API double dycGetInitd(dycClass inf, dycSlot idx);
BGBDY_API dyt dycGetInitr(dycClass inf, dycSlot idx);
BGBDY_API void *dycGetInitp(dycClass inf, dycSlot idx);
BGBDY_API void dycSetInitsb(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetInitub(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetInitss(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetInitus(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetIniti(dycClass inf, dycSlot idx, int val);
BGBDY_API void dycSetInitl(dycClass inf, dycSlot idx, s64 val);
BGBDY_API void dycSetInitf(dycClass inf, dycSlot idx, float val);
BGBDY_API void dycSetInitd(dycClass inf, dycSlot idx, double val);
BGBDY_API void dycSetInitr(dycClass inf, dycSlot idx, dyt val);
BGBDY_API void dycSetInitp(dycClass inf, dycSlot idx, void *val);
BGBDY_API int dycGetStructsb(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API int dycGetStructub(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API int dycGetStructss(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API int dycGetStructus(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API int dycGetStructi(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API s64 dycGetStructl(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API float dycGetStructf(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API double dycGetStructd(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API dyt dycGetStructr(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API void *dycGetStructp(dycClassV vinf, void *obj, dycSlot idx);
BGBDY_API void dycSetStructsb(dycClassV vinf, void *obj, dycSlot idx, int val);
BGBDY_API void dycSetStructub(dycClassV vinf, void *obj, dycSlot idx, int val);
BGBDY_API void dycSetStructss(dycClassV vinf, void *obj, dycSlot idx, int val);
BGBDY_API void dycSetStructus(dycClassV vinf, void *obj, dycSlot idx, int val);
BGBDY_API void dycSetStructi(dycClassV vinf, void *obj, dycSlot idx, int val);
BGBDY_API void dycSetStructl(dycClassV vinf, void *obj, dycSlot idx, s64 val);
BGBDY_API void dycSetStructf(dycClassV vinf, void *obj, dycSlot idx, float val);
BGBDY_API void dycSetStructd(dycClassV vinf, void *obj, dycSlot idx, double val);
BGBDY_API void dycSetStructr(dycClassV vinf, void *obj, dycSlot idx, dyt val);
BGBDY_API void dycSetStructp(dycClassV vinf, void *obj, dycSlot idx, void *val);
BGBDY_API dycObject dycNewClass(char *name);
BGBDY_API dycObject dycNewInitClass(char *name, char *sig, ...);
BGBDY_API dycObject dycNewInitClassV(char *name, char *sig, va_list args);
BGBDY_API dycObject dycNewInitClassU(char *name, char *sig, void **args);
BGBDY_API dycObject dycNew(dycClass inf);
BGBDY_API dycObject dycNewInit(dycClass inf, char *sig, ...);
BGBDY_API dycObject dycNewInitV(dycClass inf, char *sig, va_list args);
BGBDY_API dycObject dycNewInitU(dycClass inf, char *sig, void **args);
BGBDY_API void *dycCallSigU(dycObject obj, char *name, char *sig, void **args);
BGBDY_API void *dycCallSigV(dycObject obj, char *name, char *sig, va_list args);
BGBDY_API void *dycCallSig(dycObject obj, char *name, char *sig, ...);
BGBDY_API dyt dycCallSigVr(dycObject obj, char *name, char *sig, va_list lst);
BGBDY_API dyt dycCallSigUr(dycObject obj, char *name, char *sig, void **args);
BGBDY_API void *dycCallStaticSigV(dycClass inf, char *name, char *sig, va_list args);
BGBDY_API void *dycCallStaticSig(dycClass inf, char *name, char *sig, ...);
BGBDY_API dyt dycCallUr(dycObject obj, dycMethod mth, void **args);
BGBDY_API dyt dycCallVr(dycObject obj, dycMethod mth, va_list args);
BGBDY_API dyt dycCallStaticUr(dycClass inf, dycMethod mth, void **args);
BGBDY_API dyt dycCallStaticVr(dycClass inf, dycMethod mth, va_list args);
BGBDY_API int dycCallSigVi(dycObject obj, char *name, char *sig, va_list lst);
BGBDY_API s64 dycCallSigVl(dycObject obj, char *name, char *sig, va_list lst);
BGBDY_API float dycCallSigVf(dycObject obj, char *name, char *sig, va_list lst);
BGBDY_API double dycCallSigVd(dycObject obj, char *name, char *sig, va_list lst);
BGBDY_API int dycCallSigUi(dycObject obj, char *name, char *sig, void **args);
BGBDY_API s64 dycCallSigUl(dycObject obj, char *name, char *sig, void **args);
BGBDY_API float dycCallSigUf(dycObject obj, char *name, char *sig, void **args);
BGBDY_API double dycCallSigUd(dycObject obj, char *name, char *sig, void **args);
BGBDY_API int dycCallSigi(dycObject obj, char *name, char *sig, ...);
BGBDY_API s64 dycCallSigl(dycObject obj, char *name, char *sig, ...);
BGBDY_API float dycCallSigf(dycObject obj, char *name, char *sig, ...);
BGBDY_API double dycCallSigd(dycObject obj, char *name, char *sig, ...);
BGBDY_API dyt dycCallSigr(dycObject obj, char *name, char *sig, ...);
BGBDY_API void *dycCallU(dycObject obj, dycMethod mth, void **args);
BGBDY_API void *dycCallV(dycObject obj, dycMethod mth, va_list args);
BGBDY_API void *dycCall(dycObject obj, dycMethod mth, ...);
BGBDY_API int dycCallUi(dycObject obj, dycMethod mth, void **args);
BGBDY_API s64 dycCallUl(dycObject obj, dycMethod mth, void **args);
BGBDY_API float dycCallUf(dycObject obj, dycMethod mth, void **args);
BGBDY_API double dycCallUd(dycObject obj, dycMethod mth, void **args);
BGBDY_API void *dycCallUp(dycObject obj, dycMethod mth, void **args);
BGBDY_API void dycCallUv(dycObject obj, dycMethod mth, void **args);
BGBDY_API int dycCallVi(dycObject obj, dycMethod mth, va_list args);
BGBDY_API s64 dycCallVl(dycObject obj, dycMethod mth, va_list args);
BGBDY_API float dycCallVf(dycObject obj, dycMethod mth, va_list args);
BGBDY_API double dycCallVd(dycObject obj, dycMethod mth, va_list args);
BGBDY_API void *dycCallVp(dycObject obj, dycMethod mth, va_list args);
BGBDY_API void dycCallVv(dycObject obj, dycMethod mth, va_list args);
BGBDY_API int dycCalli(dycObject obj, dycMethod mth, ...);
BGBDY_API s64 dycCalll(dycObject obj, dycMethod mth, ...);
BGBDY_API float dycCallf(dycObject obj, dycMethod mth, ...);
BGBDY_API double dycCalld(dycObject obj, dycMethod mth, ...);
BGBDY_API void *dycCallp(dycObject obj, dycMethod mth, ...);
BGBDY_API void dycCallv(dycObject obj, dycMethod mth, ...);
BGBDY_API dyt dycCallr(dycObject obj, dycMethod mth, ...);
BGBDY_API void *dycCallStaticU(dycClass inf, dycMethod mth, void **args);
BGBDY_API void *dycCallStaticV(dycClass inf, dycMethod mth, va_list args);
BGBDY_API void *dycCallStatic(dycClass inf, dycMethod mth, ...);
BGBDY_API int dycCallStaticUi(dycClass inf, dycMethod mth, void **args);
BGBDY_API s64 dycCallStaticUl(dycClass inf, dycMethod mth, void **args);
BGBDY_API float dycCallStaticUf(dycClass inf, dycMethod mth, void **args);
BGBDY_API double dycCallStaticUd(dycClass inf, dycMethod mth, void **args);
BGBDY_API void *dycCallStaticUp(dycClass inf, dycMethod mth, void **args);
BGBDY_API void dycCallStaticUv(dycClass inf, dycMethod mth, void **args);
BGBDY_API int dycCallStaticVi(dycClass inf, dycMethod mth, va_list args);
BGBDY_API s64 dycCallStaticVl(dycClass inf, dycMethod mth, va_list args);
BGBDY_API float dycCallStaticVf(dycClass inf, dycMethod mth, va_list args);
BGBDY_API double dycCallStaticVd(dycClass inf, dycMethod mth, va_list args);
BGBDY_API void *dycCallStaticVp(dycClass inf, dycMethod mth, va_list args);
BGBDY_API void dycCallStaticVv(dycClass inf, dycMethod mth, va_list args);
BGBDY_API int dycCallStatici(dycClass inf, dycMethod mth, ...);
BGBDY_API s64 dycCallStaticl(dycClass inf, dycMethod mth, ...);
BGBDY_API float dycCallStaticf(dycClass inf, dycMethod mth, ...);
BGBDY_API double dycCallStaticd(dycClass inf, dycMethod mth, ...);
BGBDY_API void *dycCallStaticp(dycClass inf, dycMethod mth, ...);
BGBDY_API void dycCallStaticv(dycClass inf, dycMethod mth, ...);
BGBDY_API dyt dycCallStaticr(dycClass inf, dycMethod mth, ...);
BGBDY_API void *dycCallAsU(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API void *dycCallAsV(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API void *dycCallAs(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API int dycCallAsUi(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API s64 dycCallAsUl(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API float dycCallAsUf(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API double dycCallAsUd(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API dyt dycCallAsUr(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API void *dycCallAsUp(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API void dycCallAsUv(dycObject obj, dycClass inf, dycMethod mth, void **args);
BGBDY_API int dycCallAsVi(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API s64 dycCallAsVl(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API float dycCallAsVf(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API double dycCallAsVd(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API dyt dycCallAsVr(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API void *dycCallAsVp(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API void dycCallAsVv(dycObject obj, dycClass inf, dycMethod mth, va_list args);
BGBDY_API int dycCallAsi(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API s64 dycCallAsl(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API float dycCallAsf(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API double dycCallAsd(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API dyt dycCallAsr(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API void *dycCallAsp(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API void dycCallAsv(dycObject obj, dycClass inf, dycMethod mth, ...);
BGBDY_API void *dycCallStructU(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API void *dycCallStructV(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API void *dycCallStruct(void *obj, dycClassV vinf, dycMethod mth, ...);
BGBDY_API int dycCallStructUi(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API s64 dycCallStructUl(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API float dycCallStructUf(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API double dycCallStructUd(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API dyt dycCallStructUr(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API void *dycCallStructUp(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API void dycCallStructUv(void *obj, dycClassV vinf, dycMethod mth, void **args);
BGBDY_API int dycCallStructVi(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API s64 dycCallStructVl(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API float dycCallStructVf(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API double dycCallStructVd(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API dyt dycCallStructVr(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API void *dycCallStructVp(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API void dycCallStructVv(void *obj, dycClassV vinf, dycMethod mth, va_list args);
BGBDY_API int dycCallStructi(void *obj, dycClassV vinf, dycMethod mth, ...);
BGBDY_API s64 dycCallStructl(void *obj, dycClassV vinf, dycMethod mth, ...);
BGBDY_API float dycCallStructf(void *obj, dycClassV vinf, dycMethod mth, ...);
BGBDY_API double dycCallStructd(void *obj, dycClassV vinf, dycMethod mth, ...);
BGBDY_API dyt dycCallStructr(void *obj, dycClassV vinf, dycMethod mth, ...);
BGBDY_API void *dycCallStructp(void *obj, dycClassV vinf, dycMethod mth, ...);
BGBDY_API void dycCallStructv(void *obj, dycClassV vinf, dycMethod mth, ...);
//AHSRC:base/dyc_array.c
void BGBDYC_Array_Lock(void);
void BGBDYC_Array_Unlock(void);
dycArray dycAllocArrayHeader(void);
void dycFreeArrayHeader(dycArray arr);
BGBDY_API dycArray dycNewArray(char *sig, int cnt);
BGBDY_API dycArray dycArrayCopyValue(dycArray arr);
BGBDY_API int dycArrayDropValue(dycArray arr);
BGBDY_API int dycArrayP(dyt p);
BGBDY_API int dycArrayDataP(dyt p);
BGBDY_API int dycArray2P(dyt p);
BGBDY_API dycArray dycArrayFromData(dyt p);
BGBDY_API int dycArraySigP(dyt p, char *sig);
BGBDY_API void *dycArrayV(dycArray arr);
BGBDY_API int dycArraySz(dycArray arr);
BGBDY_API char *dycArraySig(dycArray arr);
BGBDY_API int dycArrayStep(dycArray arr);
BGBDY_API dycArray dycArrayAddOffset(dycArray arr, int offs);
BGBDY_API int dycArraySubtract(dycArray arra, dycArray arrb);
BGBDY_API dyt dycArrayIndexRef(dycArray arr, int idx);
BGBDY_API dycArray dycArrayRefArray(dyt ref);
BGBDY_API int dycArrayRefP(dyt ref);
BGBDY_API int dycArrayRefIndex(dyt ref);
BGBDY_API dyt dycArrayRefAddOffset(dyt ref, int offs);
BGBDY_API void *dycArrayIdxPtr(dycArray arr, int idx);
BGBDY_API dyt dycGetArrayVar(dycArray arr, int idx);
BGBDY_API void dycSetArrayVar(dycArray arr, int idx, dyt val);
BGBDY_API int dycGetArraysb(dycArray arr, int idx);
BGBDY_API int dycGetArrayub(dycArray arr, int idx);
BGBDY_API int dycGetArrayss(dycArray arr, int idx);
BGBDY_API int dycGetArrayus(dycArray arr, int idx);
BGBDY_API int dycGetArrayi(dycArray arr, int idx);
BGBDY_API s64 dycGetArrayl(dycArray arr, int idx);
BGBDY_API float dycGetArrayf(dycArray arr, int idx);
BGBDY_API double dycGetArrayd(dycArray arr, int idx);
BGBDY_API dyt dycGetArrayr(dycArray arr, int idx);
BGBDY_API void *dycGetArrayp(dycArray arr, int idx);
BGBDY_API u32 dycGetArrayui(dycArray arr, int idx);
BGBDY_API void dycSetArraysb(dycArray arr, int idx, int val);
BGBDY_API void dycSetArrayub(dycArray arr, int idx, int val);
BGBDY_API void dycSetArrayss(dycArray arr, int idx, int val);
BGBDY_API void dycSetArrayus(dycArray arr, int idx, int val);
BGBDY_API void dycSetArrayi(dycArray arr, int idx, int val);
BGBDY_API void dycSetArrayl(dycArray arr, int idx, s64 val);
BGBDY_API void dycSetArrayf(dycArray arr, int idx, float val);
BGBDY_API void dycSetArrayd(dycArray arr, int idx, double val);
BGBDY_API void dycSetArrayr(dycArray arr, int idx, dyt val);
BGBDY_API void dycSetArrayp(dycArray arr, int idx, void *val);
BGBDY_API bool dycArrayIdxCheck(dycArray arr, int idx);
BGBDY_API void *dycArrayIdxPtrBC(dycArray arr, int idx);
BGBDY_API int dycGetArraySsb(dycArray arr, int idx);
BGBDY_API int dycGetArraySub(dycArray arr, int idx);
BGBDY_API int dycGetArraySss(dycArray arr, int idx);
BGBDY_API int dycGetArraySus(dycArray arr, int idx);
BGBDY_API int dycGetArraySi(dycArray arr, int idx);
BGBDY_API s64 dycGetArraySl(dycArray arr, int idx);
BGBDY_API float dycGetArraySf(dycArray arr, int idx);
BGBDY_API double dycGetArraySd(dycArray arr, int idx);
BGBDY_API dyt dycGetArraySr(dycArray arr, int idx);
BGBDY_API void *dycGetArraySp(dycArray arr, int idx);
BGBDY_API void dycSetArraySsb(dycArray arr, int idx, int val);
BGBDY_API void dycSetArraySub(dycArray arr, int idx, int val);
BGBDY_API void dycSetArraySss(dycArray arr, int idx, int val);
BGBDY_API void dycSetArraySus(dycArray arr, int idx, int val);
BGBDY_API void dycSetArraySi(dycArray arr, int idx, int val);
BGBDY_API void dycSetArraySl(dycArray arr, int idx, s64 val);
BGBDY_API void dycSetArraySf(dycArray arr, int idx, float val);
BGBDY_API void dycSetArraySd(dycArray arr, int idx, double val);
BGBDY_API void dycSetArraySr(dycArray arr, int idx, dyt val);
BGBDY_API void dycSetArraySp(dycArray arr, int idx, void *val);
BGBDY_API dycArray DYC_NewArrayM_R(char *sig, int ord, int *sz);
BGBDY_API dycArray dycNewArrayM(char *sig, int ord, int *sz);
BGBDY_API dycArray dycNewArrayM2(char *sig, int sz0, int sz1);
BGBDY_API dycArray dycNewArrayM3(char *sig, int sz0, int sz1, int sz2);
BGBDY_API dycArray dycNewArrayM4(char *sig, int sz0, int sz1, int sz2, int sz3);
BGBDY_API dycArray dycNewArrayM5(char *sig,int sz0, int sz1, int sz2, int sz3, int sz4);
BGBDY_API dycArray dycNewArrayM6(char *sig,int sz0, int sz1, int sz2, int sz3, int sz4, int sz5);
BGBDY_API dycArray dycNewArrayM7(char *sig,int sz0, int sz1, int sz2, int sz3, int sz4, int sz5, int sz6);
BGBDY_API dycArray dycNewArrayM8(char *sig,int sz0, int sz1, int sz2, int sz3, int sz4, int sz5, int sz6, int sz7);
BGBDY_API dycArray dycNewArrayM9(char *sig,int sz0, int sz1, int sz2, int sz3, int sz4, int sz5, int sz6, int sz7, int sz8);
BGBDY_API dycArray dycNewArrayM10(char *sig,int sz0, int sz1, int sz2, int sz3, int sz4, int sz5, int sz6, int sz7, int sz8, int sz9);
BGBDY_API dycArray dycNewArrayM11(char *sig,int sz0, int sz1, int sz2 , int sz3, int sz4, int sz5, int sz6 , int sz7, int sz8, int sz9, int sz10);
BGBDY_API dycArray dycNewArrayM12(char *sig,int sz0, int sz1, int sz2 , int sz3, int sz4, int sz5, int sz6 , int sz7, int sz8, int sz9, int sz10, int sz11);
BGBDY_API dycArrayN dycNewArrayN(char *sig, int ord, int *sz);
BGBDY_API int dycArrayNP(dyt p);
BGBDY_API int dycArrayNSigP(dyt p, char *sig);
BGBDY_API int dycArrayNSigOrdP(dyt p, char *sig, int ord);
BGBDY_API void *dycArrayNV(dycArrayN arr);
BGBDY_API int *dycArrayNSz(dycArrayN arr);
BGBDY_API int dycArrayNCnt(dycArrayN arr);
BGBDY_API int dycArrayNOrd(dycArrayN arr);
BGBDY_API char *dycArrayNSig(dycArrayN arr);
BGBDY_API int dycArrayNStep(dycArrayN arr);
BGBDY_API void *dycArrayNIdxPtr(dycArrayN arr, int *idx);
BGBDY_API void *dycArrayNIdxPtrBC(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNsb(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNub(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNss(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNus(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNi(dycArrayN arr, int *idx);
BGBDY_API s64 dycGetArrayNl(dycArrayN arr, int *idx);
BGBDY_API float dycGetArrayNf(dycArrayN arr, int *idx);
BGBDY_API double dycGetArrayNd(dycArrayN arr, int *idx);
BGBDY_API dyt dycGetArrayNr(dycArrayN arr, int *idx);
BGBDY_API void *dycGetArrayNp(dycArrayN arr, int *idx);
BGBDY_API void dycSetArrayNsb(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNub(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNss(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNus(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNi(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNl(dycArrayN arr, int *idx, s64 val);
BGBDY_API void dycSetArrayNf(dycArrayN arr, int *idx, float val);
BGBDY_API void dycSetArrayNd(dycArrayN arr, int *idx, double val);
BGBDY_API void dycSetArrayNr(dycArrayN arr, int *idx, dyt val);
BGBDY_API void dycSetArrayNp(dycArrayN arr, int *idx, void *val);
BGBDY_API int dycGetArrayNSsb(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNSub(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNSss(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNSus(dycArrayN arr, int *idx);
BGBDY_API int dycGetArrayNSi(dycArrayN arr, int *idx);
BGBDY_API s64 dycGetArrayNSl(dycArrayN arr, int *idx);
BGBDY_API float dycGetArrayNSf(dycArrayN arr, int *idx);
BGBDY_API double dycGetArrayNSd(dycArrayN arr, int *idx);
BGBDY_API dyt dycGetArrayNSr(dycArrayN arr, int *idx);
BGBDY_API void *dycGetArrayNSp(dycArrayN arr, int *idx);
BGBDY_API void dycSetArrayNSsb(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNSub(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNSss(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNSus(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNSi(dycArrayN arr, int *idx, int val);
BGBDY_API void dycSetArrayNSl(dycArrayN arr, int *idx, s64 val);
BGBDY_API void dycSetArrayNSf(dycArrayN arr, int *idx, float val);
BGBDY_API void dycSetArrayNSd(dycArrayN arr, int *idx, double val);
BGBDY_API void dycSetArrayNSr(dycArrayN arr, int *idx, dyt val);
BGBDY_API void dycSetArrayNSp(dycArrayN arr, int *idx, void *val);
BGBDY_API void *dycArray2IdxPtr(dycArrayN arr, int y, int x);
BGBDY_API void *dycArray2IdxPtrBC(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2sb(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2ub(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2ss(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2us(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2i(dycArrayN arr, int y, int x);
BGBDY_API s64 dycGetArray2l(dycArrayN arr, int y, int x);
BGBDY_API float dycGetArray2f(dycArrayN arr, int y, int x);
BGBDY_API double dycGetArray2d(dycArrayN arr, int y, int x);
BGBDY_API dyt dycGetArray2r(dycArrayN arr, int y, int x);
BGBDY_API void *dycGetArray2p(dycArrayN arr, int y, int x);
BGBDY_API void dycSetArray2sb(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2ub(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2ss(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2us(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2i(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2l(dycArrayN arr, int y, int x, s64 val);
BGBDY_API void dycSetArray2f(dycArrayN arr, int y, int x, float val);
BGBDY_API void dycSetArray2d(dycArrayN arr, int y, int x, double val);
BGBDY_API void dycSetArray2r(dycArrayN arr, int y, int x, dyt val);
BGBDY_API void dycSetArray2p(dycArrayN arr, int y, int x, void *val);
BGBDY_API int dycGetArray2Ssb(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2Sub(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2Sss(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2Sus(dycArrayN arr, int y, int x);
BGBDY_API int dycGetArray2Si(dycArrayN arr, int y, int x);
BGBDY_API s64 dycGetArray2Sl(dycArrayN arr, int y, int x);
BGBDY_API float dycGetArray2Sf(dycArrayN arr, int y, int x);
BGBDY_API double dycGetArray2Sd(dycArrayN arr, int y, int x);
BGBDY_API dyt dycGetArray2Sr(dycArrayN arr, int y, int x);
BGBDY_API void *dycGetArray2Sp(dycArrayN arr, int y, int x);
BGBDY_API void dycSetArray2Ssb(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2Sub(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2Sss(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2Sus(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2Si(dycArrayN arr, int y, int x, int val);
BGBDY_API void dycSetArray2Sl(dycArrayN arr, int y, int x, s64 val);
BGBDY_API void dycSetArray2Sf(dycArrayN arr, int y, int x, float val);
BGBDY_API void dycSetArray2Sd(dycArrayN arr, int y, int x, double val);
BGBDY_API void dycSetArray2Sr(dycArrayN arr, int y, int x, dyt val);
BGBDY_API void dycSetArray2Sp(dycArrayN arr, int y, int x, void *val);
BGBDY_API void *dycArray3IdxPtr(dycArrayN arr, int z, int y, int x);
BGBDY_API void *dycArray3IdxPtrBC(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3sb(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3ub(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3ss(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3us(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3i(dycArrayN arr, int z, int y, int x);
BGBDY_API s64 dycGetArray3l(dycArrayN arr, int z, int y, int x);
BGBDY_API float dycGetArray3f(dycArrayN arr, int z, int y, int x);
BGBDY_API double dycGetArray3d(dycArrayN arr, int z, int y, int x);
BGBDY_API dyt dycGetArray3r(dycArrayN arr, int z, int y, int x);
BGBDY_API void *dycGetArray3p(dycArrayN arr, int z, int y, int x);
BGBDY_API void dycSetArray3sb(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3ub(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3ss(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3us(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3i(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3l(dycArrayN arr, int z, int y, int x, s64 val);
BGBDY_API void dycSetArray3f(dycArrayN arr, int z, int y, int x, float val);
BGBDY_API void dycSetArray3d(dycArrayN arr, int z, int y, int x, double val);
BGBDY_API void dycSetArray3r(dycArrayN arr, int z, int y, int x, dyt val);
BGBDY_API void dycSetArray3p(dycArrayN arr, int z, int y, int x, void *val);
BGBDY_API int dycGetArray3Ssb(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3Sub(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3Sss(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3Sus(dycArrayN arr, int z, int y, int x);
BGBDY_API int dycGetArray3Si(dycArrayN arr, int z, int y, int x);
BGBDY_API s64 dycGetArray3Sl(dycArrayN arr, int z, int y, int x);
BGBDY_API float dycGetArray3Sf(dycArrayN arr, int z, int y, int x);
BGBDY_API double dycGetArray3Sd(dycArrayN arr, int z, int y, int x);
BGBDY_API dyt dycGetArray3Sr(dycArrayN arr, int z, int y, int x);
BGBDY_API void *dycGetArray3Sp(dycArrayN arr, int z, int y, int x);
BGBDY_API void dycSetArray3Ssb(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3Sub(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3Sss(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3Sus(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3Si(dycArrayN arr, int z, int y, int x, int val);
BGBDY_API void dycSetArray3Sl(dycArrayN arr, int z, int y, int x, s64 val);
BGBDY_API void dycSetArray3Sf(dycArrayN arr, int z, int y, int x, float val);
BGBDY_API void dycSetArray3Sd(dycArrayN arr, int z, int y, int x, double val);
BGBDY_API void dycSetArray3Sr(dycArrayN arr, int z, int y, int x, dyt val);
BGBDY_API void dycSetArray3Sp(dycArrayN arr, int z, int y, int x, void *val);
