LIBVECMATH_SRCS = \
	math_m3.c \
	math_m4.c \
	math_mf.c \
	math_n.c \
	math_plane.c \
	math_quat.c \
	math_v3f.c \
	math_vnf.c \
	math_hullf.c \
	mathlib_d.c \
	mathlib_f.c \
	\
	math_solid.c \
	math_vecnf.c \
	\
	wint/math_wint.c

