//bggl3_types.c
int BGGL3_IndexType(char *name);
void BGGL3_InitHeap();
elem BGGL3_Alloc(char *type, int sz);
int BGGL3_GetTypeID(elem p);
char *BGGL3_GetType(elem p);
int BGGL3_GetSize(elem p);
char *BGGL3_AllocSymbol(char *s);
char *BGGL3_AllocKeyword(char *s);
char *BGGL3_AllocString(char *s);
elem BGGL3_HashSymbol(char *name);
elem BGGL3_HashKeyword(char *name);
elem BGGL3_HashString(char *name);
elem BGGL3_CONS(elem a, elem b);
elem BGGL3_CAR(elem a);
elem BGGL3_CDR(elem a);
elem BGGL3_CADR(elem a);
elem BGGL3_CDDR(elem a);
elem BGGL3_CADDR(elem a);
elem BGGL3_CDDDR(elem a);
elem BGGL3_CADDDR(elem a);
elem BGGL3_CDDDDR(elem a);
elem BGGL3_CADDDDR(elem a);
elem BGGL3_CDDDDDR(elem a);
elem BGGL3_CADDDDDR(elem a);
elem BGGL3_CDDDDDDR(elem a);
void BGGL3_CARN(elem a, elem b);
void BGGL3_CDRN(elem a, elem b);
elem BGGL3_INT(int i);
elem BGGL3_FLOAT(float f);
elem BGGL3_COMPLEX(float f, float g);
int BGGL3_TOINT(elem a);
float BGGL3_TOFLOAT(elem a);
float BGGL3_GETREAL(elem a);
float BGGL3_GETIMAG(elem a);
void BGGL3_Print(elem a);
elem BGGL3_LIST2(elem a, elem b);
elem BGGL3_LIST3(elem a, elem b, elem c);
int BGGL3_ListLength(elem a);
int BGGL3_CONSP(elem a);
int BGGL3_SYMBOLP(elem a);
int BGGL3_KEYWORDP(elem a);
int BGGL3_STRINGP(elem a);
int BGGL3_INTP(elem a);
int BGGL3_FLOATP(elem a);
int BGGL3_COMPLEXP(elem a);
int BGGL3_NUMBERP(elem a);
int BGGL3_FVECTORP(elem a);
elem BGGL3_List2FVector(elem a);
elem BGGL3_MakeFVector(float *va, int n);
void BGGL3_ToVector(elem a, float *va);
//bggl3_parse.c
int BGGL3_Linenum(char *buf);
void BGGL3_Warning(char *buf, char *str, ...);
void BGGL3_Error(char *buf, char *str, ...);
char *BGGL3_EatWhite(char *s);
char *BGGL3_ParseToken(char *s, char *b, int *ty);
char *BGGL3_EatToken(char *s);
elem BGGL3_ParseListItem(char **str);
elem BGGL3_ParseExprInner(char **str);
elem BGGL3_ParseExprDot(char **str);
elem BGGL3_ParseExprExp(char **str);
elem BGGL3_ParseExprMD(char **str);
elem BGGL3_ParseExprAS(char **str);
elem BGGL3_ParseExprCmp(char **str);
elem BGGL3_ParseExprEQ(char **str);
elem BGGL3_ParseExpr(char **str);
elem BGGL3_EvalString(BGGL3_State *ctx, char *name, char *buf);
elem BGGL3_LoadFile(BGGL3_State *ctx, char *name);
//bggl3_interp.c
BGGL3_State *BGGL3_NewContext();
BGGL3_Binding *BGGL3_AllocBinding();
void BGGL3_BindValue(char *name, char *desc, elem val);
void BGGL3_AddBuiltin(char *name, char *desc,elem (*func)(BGGL3_State *ctx, elem args), int n);
elem BGGL3_LookupList(BGGL3_Binding *lst, elem expr);
elem BGGL3_AssignList(BGGL3_Binding *lst, elem var, elem val);
elem BGGL3_EvalList(BGGL3_State *ctx, elem cur);
BGGL3_Binding *BGGL3_FillArgs(BGGL3_Binding *lst, elem vars);
BGGL3_Binding *BGGL3_BindArgs(BGGL3_Binding *lst, elem vars, elem vals);
BGGL3_Binding *BGGL3_SetArgs(BGGL3_Binding *lst, elem vars, elem vals);
elem BGGL3_EvalExprApply(BGGL3_State *ctx, elem expr);
elem BGGL3_EvalExpr(BGGL3_State *ctx, elem expr);
elem BGGL3_ApplyArgs(BGGL3_State *ctx, elem b, elem c);
elem BGGL3_ApplyArg(BGGL3_State *ctx, elem fcn, elem arg);
//bggl3_builtin.c
elem bggl3_print(BGGL3_State *ctx, elem args);
elem bggl3_println(BGGL3_State *ctx, elem args);
elem bggl3_sqrt(BGGL3_State *ctx, elem args);
elem bggl3_log2(BGGL3_State *ctx, elem args);
elem bggl3_log10(BGGL3_State *ctx, elem args);
elem bggl3_ln(BGGL3_State *ctx, elem args);
elem bggl3_log(BGGL3_State *ctx, elem args);
elem bggl3_floor(BGGL3_State *ctx, elem args);
elem bggl3_ceil(BGGL3_State *ctx, elem args);
elem bggl3_round(BGGL3_State *ctx, elem args);
elem bggl3_sin(BGGL3_State *ctx, elem args);
elem bggl3_cos(BGGL3_State *ctx, elem args);
elem bggl3_tan(BGGL3_State *ctx, elem args);
elem bggl3_asin(BGGL3_State *ctx, elem args);
elem bggl3_acos(BGGL3_State *ctx, elem args);
elem bggl3_atan(BGGL3_State *ctx, elem args);
elem bggl3_atan2(BGGL3_State *ctx, elem args);
elem bggl3_real(BGGL3_State *ctx, elem args);
elem bggl3_imag(BGGL3_State *ctx, elem args);
elem bggl3_abs(BGGL3_State *ctx, elem args);
elem bggl3_angle(BGGL3_State *ctx, elem args);
elem bggl3_conj(BGGL3_State *ctx, elem args);
elem bggl3_fact(BGGL3_State *ctx, elem args);
elem bggl3_graph(BGGL3_State *ctx, elem args);
elem bggl3_load(BGGL3_State *ctx, elem args);
elem bggl3_dumpmesh(BGGL3_State *ctx, elem args);
void BGGL3_InitBuiltin();
//bggl3_builtin_graph.c
int Img_StoreTGA(FILE *fd, unsigned char *buf, int w, int h);
elem bggl3_graph(BGGL3_State *ctx, elem args);
//bggl3_builtin_vector.c
elem bggl3_len(BGGL3_State *ctx, elem args);
elem bggl3_norm(BGGL3_State *ctx, elem args);
elem bggl3_ndot(BGGL3_State *ctx, elem args);
elem bggl3_npoint(BGGL3_State *ctx, elem args);
elem bggl3_ndir(BGGL3_State *ctx, elem args);
elem bggl3_ndist(BGGL3_State *ctx, elem args);
void BGGL3_InitBuiltinVector();
//bggl3_builtin_opr.c
elem bggl3_add(BGGL3_State *ctx, elem args);
elem bggl3_sub(BGGL3_State *ctx, elem args);
elem bggl3_mul(BGGL3_State *ctx, elem args);
elem bggl3_div(BGGL3_State *ctx, elem args);
elem bggl3_idiv(BGGL3_State *ctx, elem args);
elem bggl3_mod(BGGL3_State *ctx, elem args);
elem bggl3_exp(BGGL3_State *ctx, elem args);
elem bggl3_neg(BGGL3_State *ctx, elem args);
elem bggl3_cmpl(BGGL3_State *ctx, elem args);
elem bggl3_cmpg(BGGL3_State *ctx, elem args);
elem bggl3_cmple(BGGL3_State *ctx, elem args);
elem bggl3_cmpge(BGGL3_State *ctx, elem args);
elem bggl3_cmpe(BGGL3_State *ctx, elem args);
elem bggl3_cmpne(BGGL3_State *ctx, elem args);
void BGGL3_InitBuiltinOpr();
//bggl3.c
elem bggl3_quit(BGGL3_State *ctx, elem args);
int main(int argc, char *argv[]);
