//AHSRC:base/frir_api.c
BGBFRIR_API FRIR_Method *FRIR_AllocMethod();
BGBFRIR_API FRIR_Opcode *FRIR_AllocMethodOpcode(FRIR_Method *mth);
BGBFRIR_API FRIR_Trace *FRIR_AllocMethodTrace(FRIR_Method *mth);
BGBFRIR_API FRIR_Trace *FRIR_EndTrace(FRIR_Method *mth);
BGBFRIR_API void FRIR_EmitLabel(FRIR_Method *mth, int lbl);
BGBFRIR_API void FRIR_EmitJump(FRIR_Method *mth, int lbl);
BGBFRIR_API void FRIR_EmitOpJccAI(FRIR_Method *mth, int opnum, int a, s32 i, int lbl);
BGBFRIR_API void FRIR_EmitRet(FRIR_Method *mth, int reg);
BGBFRIR_API void FRIR_EmitOpV(FRIR_Method *mth, int opnum);
BGBFRIR_API void FRIR_EmitOpCAB(FRIR_Method *mth, int opnum, int c, int a, int b);
BGBFRIR_API void FRIR_EmitOpCA(FRIR_Method *mth, int opnum, int c, int a);
BGBFRIR_API void FRIR_EmitOpCAI(FRIR_Method *mth, int opnum, int c, int a, s32 i);
BGBFRIR_API void FRIR_EmitOpCAL(FRIR_Method *mth, int opnum, int c, int a, s64 i);
BGBFRIR_API void FRIR_EmitOpCAF(FRIR_Method *mth, int opnum, int c, int a, f32 i);
BGBFRIR_API void FRIR_EmitOpCAD(FRIR_Method *mth, int opnum, int c, int a, f64 i);
BGBFRIR_API void FRIR_EmitOpCI(FRIR_Method *mth, int opnum, int c, s32 i);
BGBFRIR_API void FRIR_EmitOpCL(FRIR_Method *mth, int opnum, int c, s64 l);
BGBFRIR_API void FRIR_EmitOpCF(FRIR_Method *mth, int opnum, int c, f32 f);
BGBFRIR_API void FRIR_EmitOpCD(FRIR_Method *mth, int opnum, int c, f64 d);
BGBFRIR_API void FRIR_EmitOpCallS(FRIR_Method *mth, int opnum, int ret, char *name, char *sig, int *args, int nargs);
//AHSRC:base/frir_call.c
BGBFRIR_API FRIR_StaticMethodInfo *FRIR_LookupStaticMethod(char *path, char *name, char *sig);
BGBFRIR_API FRIR_StaticMethodInfo *FRIR_LookupStaticMethod(char *path, char *name, char *sig);
BGBFRIR_API FRIR_MethodCallInfo *FRIR_AllocMethodCallInfo();
BGBFRIR_API FRIR_Context *FRIR_AllocContext();
BGBFRIR_API FRIR_Frame *FRIR_Thread_NewFrame(FRIR_Context *ctx);
BGBFRIR_API FRIR_Frame *FRIR_Thread_PushFrame(FRIR_Context *ctx);
BGBFRIR_API FRIR_Frame *FRIR_Thread_PopFrame(FRIR_Context *ctx);
BGBFRIR_API void FRIR_Thread_ApplyMethod(FRIR_Context *ctx,FRIR_Method *mth, FRIR_Value **args, int nargs);
FRIR_Trace *FRIR_ThOpE_RET(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_RETV(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_CALL_S(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
//AHSRC:base/frir_ops.c
//AHSRC:base/frir_jumpcc.c
BGBFRIR_API FRIR_Trace *FRIR_ThOpE_NOP(FRIR_Context *ctx,FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_I(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_L(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_F(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_D(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_A(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_I(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_L(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_F(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_D(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_A(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_I(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_L(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_F(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_D(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_A(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_I(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_L(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_F(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_D(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_A(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_I(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_L(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_F(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_D(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_A(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_I(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_L(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_F(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_D(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_A(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_IC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_LC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_FC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_DC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_IC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_LC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_FC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_DC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_IC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_LC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_FC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_DC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_IC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_LC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_FC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_DC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_IC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_LC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_FC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_DC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_IC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_LC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_FC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_DC(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LT_IZ(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GT_IZ(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_LE_IZ(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_GE_IZ(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_EQ_IZ(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
FRIR_Trace *FRIR_ThOpE_JMP_NE_IZ(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
//AHSRC:base/frir_thread.c
FRIR_OpHandlerFcn FRIR_FetchOpcodeHandlerI(int opnum);
BGBFRIR_API FRIR_OpHandlerFcn FRIR_FetchOpcodeHandler(int opnum);
FRIR_TraceEndFcn FRIR_FetchOpcodeEndHandlerI(int opnum);
BGBFRIR_API FRIR_TraceEndFcn FRIR_FetchOpcodeEndHandler(int opnum);
BGBFRIR_API FRIR_Trace *FRIR_Trace_FindTargetForLabel(FRIR_Trace *tr, int lbl);
BGBFRIR_API FRIR_Trace *FRIR_Trace_EndDefault(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
BGBFRIR_API FRIR_Trace *FRIR_Trace_EndJumpDefault(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
BGBFRIR_API FRIR_Trace *FRIR_Trace_EndDefault_BadOpcode(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
BGBFRIR_API FRIR_Trace *FRIR_Trace_EndJumpDefInit(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
BGBFRIR_API FRIR_Trace *FRIR_Trace_EndJccDefInit(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
BGBFRIR_API FRIR_Trace *FRIR_Trace_EndRetDefInit(FRIR_Context *ctx, FRIR_Trace *tr, FRIR_Opcode *op);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJmp(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault1(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault2(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault3(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault4(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault5(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault6(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault7(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefault8(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ1(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ2(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ3(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ4(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ5(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ6(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ7(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJ8(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc1(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc2(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc3(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc4(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc5(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc6(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc7(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API FRIR_Trace *FRIR_Trace_RunDefaultJcc8(FRIR_Context *ctx, FRIR_Trace *tr);
BGBFRIR_API void FRIR_Thread_RunStep(FRIR_Context *ctx);
//AHSRC:base/frir_threadop.c
BGBFRIR_API void FRIR_ThOp_NOP(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_ADD_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_ADD_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_ADD_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_ADD_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_ADD_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SUB_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SUB_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SUB_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SUB_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SUB_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MUL_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MUL_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MUL_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MUL_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MUL_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_DIV_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_DIV_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_DIV_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_DIV_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_DIV_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOD_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOD_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_AND_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_AND_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_OR_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_OR_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_XOR_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_XOR_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHL_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHL_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHR_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHR_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHRR_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHRR_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_NEG_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_NEG_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_NEG_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_NEG_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_NOT_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_NOT_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_FC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_DC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOV_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_I2L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_I2F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_I2D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_I2A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_L2I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_L2F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_L2D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_L2A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_F2I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_F2L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_F2D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_D2I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_D2L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_D2F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_A2I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CONV_A2L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA_B(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA_S(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA2_B(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA2_S(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA2_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA2_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA2_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA2_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LEA2_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLLOAD_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLLOAD_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLLOAD_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLLOAD_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLLOAD_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLSTORE_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLSTORE_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLSTORE_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLSTORE_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LLSTORE_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LALOAD_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LALOAD_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LALOAD_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LALOAD_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LALOAD_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LASTORE_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LASTORE_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LASTORE_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LASTORE_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LASTORE_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXLOAD_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXLOAD_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXLOAD_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXLOAD_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXLOAD_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXSTORE_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXSTORE_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXSTORE_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXSTORE_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_LXSTORE_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_I(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_L(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_F(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_D(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_A(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_FC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LT_DC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_FC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GT_DC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_FC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_LE_DC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_FC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_GE_DC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_FC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_EQ_DC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_FC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_CMP_NE_DC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_ADD_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_ADD_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SUB_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SUB_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MUL_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MUL_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_DIV_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_DIV_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOD_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_MOD_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_AND_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_AND_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_OR_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_OR_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_XOR_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_XOR_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHL_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHL_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHR_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHR_LC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHRR_IC(FRIR_Context *ctx, FRIR_Opcode *op);
BGBFRIR_API void FRIR_ThOp_SHRR_LC(FRIR_Context *ctx, FRIR_Opcode *op);
