BUILD=.
MKSUF=.msvc
LIBSUF=.lib
DLLSUF=.dll
EXESUF=.exe
OBJSUF=.obj
BINSUF=.exe
DLLPF=

CC_OUTEXE=cl /Fe
CC_OUTDLL=cl /LD /Fe
CC_OUTOBJ=cl /c /Fo
CC_OUTTOOL=cl /Fe

CFLAGS = /Iinclude /I../include /DLIBBMID_C
CFLAGS_DLL = /Iinclude /I../include /DLIBBMID_C /DBGBMID_DLL /O2 /Zi \
	/arch:SSE2 /MP \
	../libvecmath.lib ../bgbdy.lib ../bgbgc.lib winmm.lib
CFLAGS_APP = /Iinclude /I../include libbgbmid.lib /Zi \
	../libvecmath.lib ../bgbdy.lib ../bgbgc.lib winmm.lib

include Makefile.inc
