#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char *in_txt;
char *out_c, *out_var;

char *lines[65536];
int n_lines;

char *kralloc_buffer=NULL;
int kralloc_pos=0;

void *kralloc(int sz)
{
	char *s;

	if(!kralloc_buffer)kralloc_buffer=malloc(262144);
	if((kralloc_pos+sz)>=262144)kralloc_pos=0;

	s=kralloc_buffer+kralloc_pos;
	kralloc_pos+=sz;
	return((void *)s);
}

char **ksplit(char *s)
{
	char **a, *t;
	int i;

	a=kralloc(64*sizeof(char *));
	i=0;
	while(*s)
	{
		while(*s && (*s<=' '))s++;
		if(!*s)break;
		if(*s=='#')break;
		if(*s==';')break;
		if((s[0]=='/') && (s[1]=='/'))
			break;

		t=kralloc(256);
		a[i++]=t;

		if(*s=='"')
		{
			s++;
			while(*s && (*s!='"'))*t++=*s++;
			if(*s=='"')s++;

			*t++=0;
			continue;
		}

		while(*s && (*s>' '))*t++=*s++;
		*t++=0;
	}
	a[i]=NULL;

	return(a);
}

int is_sfi(char *s)
{
	while(*s)
	{
		if(*s=='=')return(1);
		s++;
	}
	return(0);
}

int main(int argc, char *argv[])
{
	char buf[256];
	FILE *fd;
	char *s, *t, **a;
	int i, j, k, l, n;

	if(argc>=3)
	{
		in_txt=strdup(argv[1]);
		out_c=strdup(argv[2]);
		out_var=strdup(argv[3]);
	}else
	{
		printf("Usage: %s <in_txt> <out_c> <var_name>\n", argv[0]);
		return(-1);
	}

	memset(lines, 0, 65536*sizeof(char *));
	n_lines=0;

	fd=fopen(in_txt, "rt");
	if(!fd)
	{
		printf("fail open %s\n", in_txt);
		return(-1);
	}

	while(!feof(fd))
	{
		memset(buf, 0, 256);
		fgets(buf, 255, fd);

		s=buf;
		while(*s && (*s<=' '))s++;
//		if(!*s)continue;
//		if(*s==';')continue;
//		if(*s=='#')continue;
//		if(*s=='/')continue;

		lines[n_lines++]=strdup(buf);

#if 0
		a=ksplit(s);
		if(!a[0])continue;
#endif
	}
	fclose(fd);

	fd=fopen(out_c, "wt");
	if(!fd)
	{
		printf("can't open output %s\n", out_c);
		return(-1);
	}

	fprintf(fd, "/* Autogenerated source */\n");

	fprintf(fd, "char *%s=\n\"", out_var);
	j=1;
	for(i=0; i<n_lines; i++)
	{
		s=lines[i]; t=buf;
		while(*s)
		{
			if((*s<' ') || (*s>'~'))
			{
				if(*s=='\r')
					{ s++; *t++='\\'; *t++='r'; continue; }
				if(*s=='\n')
					{ s++; *t++='\\'; *t++='n'; continue; }
				if(*s=='\t')
					{ s++; *t++='\\'; *t++='t'; continue; }

				sprintf(t, "\\x%02X", (*s++)&0xFF);
				t+=4; continue;
			}
			if(*s=='\\')
				{ s++; *t++='\\'; *t++='\\'; continue; }
			if(*s=='\"')
				{ s++; *t++='\\'; *t++='\"'; continue; }
			*t++=*s++;
		}
		*t++=0;

		if((j+strlen(buf))>72)
		{
			fprintf(fd, "\"\n\"");
			j=1;
		}

		fprintf(fd, "%s", buf);
		j+=strlen(buf);
	}
	fprintf(fd, "\";\n\n");
	fclose(fd);

	return(0);
}
