//AHSRC:base/fri_context.c
FRBC2CI_API FR2CI_Context *FR2CI_AllocContext(FR2CI_LoaderCtx *ldr);
FRBC2CI_API int FR2CI_RunContext(FR2CI_Context *ctx);
FR2CI_Frame *FR2CI_AllocFrame(FR2CI_Context *ctx);
void FR2CI_FreeFrame(FR2CI_Context *ctx, FR2CI_Frame *op);
void FR2CI_PushNewFrame(FR2CI_Context *ctx);
void *FR2CI_ContextPoolAlloc(FR2CI_Context *img, int sz);
void FR2CI_ContextPoolFree(FR2CI_Context *img, void *ptr, int sz);
void FR2CI_SetupFrameRegs(FR2CI_Context *ctx, FR2CI_Frame *frm, int nreg);
void FR2CI_SetupFrameArgs(FR2CI_Context *ctx, FR2CI_Frame *frm, int narg);
void FR2CI_SetupFrameLocals(FR2CI_Context *ctx, FR2CI_Frame *frm, int nloc);
void FR2CI_CleanupFrame(FR2CI_Context *ctx, FR2CI_Frame *frm);
FR2CI_CleanupOpcode *FR2CI_FrameNewCleanupOp(FR2CI_Context *ctx, FR2CI_Frame *frm);
FR2CI_CleanupOpcode *FR2CI_AllocCleanupOpcode(FR2CI_Context *img);
void FR2CI_FreeCleanupOpcode(FR2CI_Context *img, FR2CI_CleanupOpcode *op);
void FR2CI_Op_BenchNop0(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_BenchNop1(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_BenchNop2(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_BenchNop3(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_BenchArith0(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_BenchArith1(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_BenchArith2(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_BenchArith3(FR2CI_Frame *frm, FR2CI_Opcode *op);
FR2CI_Trace *FR2CI_TailOp_BenchNext0(FR2CI_Frame *frm, FR2CI_TailOpcode *op);
FRBC2CI_API int FR2CI_SetupNopBench(FR2CI_Context *ctx);
//AHSRC:base/fri_function.c
int FR2CI_DecodeCharUTF8(byte **rcs);
s64 FR2CI_DecodeVLIE(byte **rcs);
s64 FR2CI_DecodeSVLIE(byte **rcs);
char *FR2CI_DecodeMarkerString(FR2CI_Image *img,byte **rcs, byte *cse);
char *FR2CI_DecodeIndexString(FR2CI_Image *img,byte **rcs, byte *cse);
FR2CI_Function *FR2CI_DecodeFunction(FR2CI_Image *img,byte *data, int sz);
FR2CI_VarInfo *FR2CI_DecodeVarInfo(FR2CI_Image *img,byte *data, int dsz);
void FR2CI_InitVarInfo(FR2CI_Image *img,FR2CI_VarInfo *tmp, FR2CI_Value *init);
FR2CI_Trace *FR2CI_GetFunctionEntryTrace(FR2CI_Function *func);
FR2CI_Trace *FR2CI_GetFunctionImportEntryTrace(FR2CI_Function *func);
FR2CI_Trace *FR2CI_LookupFunctionTrace(FR2CI_Function *func, byte *ip);
FR2CI_Trace *FR2CI_DecodeFunctionTraces(FR2CI_Function *func);
//AHSRC:base/fri_image.c
void *fr2ci_malloc(int sz);
void fr2ci_free(void *ptr);
char *fr2ci_strdup(char *str);
FR2CI_Image *FR2CI_AllocImage(void);
FR2CI_Image *FR2CI_DecodeImage(byte *data, int szData, int flags);
int FR2CI_GetGIDX(FR2CI_Image *img, int idx);
int FR2CI_GetLIDX(FR2CI_Image *img, int idx);
int FR2CI_DecodeMarkerTWOCC(FR2CI_Image *img, u16 tcc, byte *css, byte *cse);
int FR2CI_DecodeMarkerFOURCC(FR2CI_Image *img, u32 fcc, byte *css, byte *cse);
FR2CI_Opcode *FR2CI_AllocOpcode(FR2CI_Image *img);
void FR2CI_FreeOpcode(FR2CI_Image *img, FR2CI_Opcode *op);
FR2CI_Trace *FR2CI_AllocTrace(FR2CI_Image *img);
void FR2CI_FreeTrace(FR2CI_Image *img, FR2CI_Trace *op);
FR2CI_TailOpcode *FR2CI_AllocTailOpcode(FR2CI_Image *img);
void FR2CI_FreeTailOpcode(FR2CI_Image *img, FR2CI_TailOpcode *op);
s16 fr2ci_getInt16BE(byte *ptr);
u16 fr2ci_getUInt16BE(byte *ptr);
s32 fr2ci_getInt24BE(byte *ptr);
u32 fr2ci_getUInt24BE(byte *ptr);
s32 fr2ci_getInt32BE(byte *ptr);
u32 fr2ci_getUInt32BE(byte *ptr);
s64 fr2ci_getInt64BE(byte *ptr);
u64 fr2ci_getUInt64BE(byte *ptr);
s64 fr2ci_getInt56BE(byte *ptr);
u64 fr2ci_getUInt56BE(byte *ptr);
s32 FR2CI_GetImageLiteralInt32(FR2CI_Image *img, int idx);
u32 FR2CI_GetImageLiteralUInt32(FR2CI_Image *img, int idx);
s64 FR2CI_GetImageLiteralInt64(FR2CI_Image *img, int idx);
u64 FR2CI_GetImageLiteralUInt64(FR2CI_Image *img, int idx);
f32 FR2CI_GetImageLiteralFloat32(FR2CI_Image *img, int idx);
f64 FR2CI_GetImageLiteralFloat64(FR2CI_Image *img, int idx);
void FR2CI_SplitIndexValuePrefix(int idx, int *rval, int *rpfx);
void *FR2CI_GetImageLiteralPointer(FR2CI_Image *img, int idx);
void *FR2CI_GetImageLiteralTablePointer(FR2CI_Image *img, int idx);
FR2CI_LiteralInfo *FR2CI_DecodeLiteralTableEntry(FR2CI_Image *img, int idx);
void FR2CI_InitLiteralInfo(FR2CI_Image *img,FR2CI_LiteralInfo *tmp, FR2CI_Value *init);
void *FR2CI_GetImageGlobalTableObjPointer(FR2CI_Image *img, int idx);
void *FR2CI_ImagePoolAlloc(FR2CI_Image *img, int sz);
void FR2CI_ImagePoolFree(FR2CI_Image *img, void *ptr, int sz);
FR2CI_ArgOpcode *FR2CI_AllocArgOpcode(FR2CI_Image *img);
void FR2CI_FreeArgOpcode(FR2CI_Image *img, FR2CI_ArgOpcode *op);
FR2CI_CallInfo *FR2CI_AllocCallInfo(FR2CI_Image *img);
void FR2CI_FreeCallInfo(FR2CI_Image *img, FR2CI_CallInfo *op);
FR2CI_Function *FR2CI_AllocFunction(FR2CI_Image *img);
void FR2CI_FreeFunction(FR2CI_Image *img, FR2CI_Function *op);
FR2CI_VarInfo *FR2CI_AllocVarInfo(FR2CI_Image *img);
void FR2CI_FreeVarInfo(FR2CI_Image *img, FR2CI_VarInfo *op);
FR2CI_Function *FR2CI_ImageGetFunction(FR2CI_Image *img, int idx);
FR2CI_Function *FR2CI_ImageGetExportFunction(FR2CI_Image *img, char *name, char *sig);
FR2CI_LiteralInfo *FR2CI_AllocFR2CI_LiteralInfo(FR2CI_Image *img);
void FR2CI_FreeFR2CI_LiteralInfo(FR2CI_Image *img, FR2CI_LiteralInfo *op);
//AHSRC:base/fri_loader.c
FRBC2CI_API FR2CI_LoaderCtx *FR2CI_AllocLoader(void);
FRBC2CI_API FR2CI_Image *FR2CI_LookupImageName(FR2CI_LoaderCtx *ldr, char *name);
FRBC2CI_API FR2CI_Image *FR2CI_LoadImageName(FR2CI_LoaderCtx *ldr, char *name);
FRBC2CI_API FR2CI_Image *FR2CI_LoadProgramName(FR2CI_LoaderCtx *ldr, char *name);
FRBC2CI_API FR2CI_Function *FR2CI_LookupFunctionNameGeneric(FR2CI_LoaderCtx *ldr, char *name, char *sig);
//AHSRC:base/fri_natcall.c
char *FR2CI_ParseSigFindNext(FR2CI_Image *img, char *sig);
int FR2CI_ParseSigBaseType5(FR2CI_Image *img, char *sig);
FR2CI_TailOpcode *FR2CI_MakeOpNatCall(FR2CI_Image *img, void *fcn, char *sig);
FR2CI_Trace *FR2CI_GetFunctionNativeCall(FR2CI_Image *img, FR2CI_Function *func, char *name, char *sig);
void *FR2CI_FFI_LookupLabel(char *name);
int FR2CI_FFI_LookupBlacklist(char *name);
void FR2CI_FFI_AddExeSection(char *name, s64 va, s64 sz, int fl);
void FR2CI_FFI_AddProxyPtr(char *name, void *ptr);
void *FR2CI_FFI_FetchSym(char *name);
//AHSRC:base/fri_opcode.c
s32 FR2CI_ConstOrLit12I(FR2CI_Image *img, int opr, int imm);
s64 FR2CI_ConstOrLit12L(FR2CI_Image *img, int opr, int imm);
double FR2CI_ConstOrLit12F(FR2CI_Image *img, int opr, int imm);
double FR2CI_ConstOrLit12D(FR2CI_Image *img, int opr, int imm);
FR2CI_Opcode *FR2CI_DecodeOpcode2B(FR2CI_Image *img,byte **rcs, byte *cse, int pfx);
FR2CI_Opcode *FR2CI_DecodeOpcode(FR2CI_Image *img,byte **rcs, byte *cse);
FR2CI_TailOpcode *FR2CI_DecodeTailOpcode(FR2CI_Image *img,byte **rcs, byte *cse);
//AHSRC:base/fri_struct.c
FR2CI_LiteralInfo *FR2CI_DecodeStruct(FR2CI_Image *img,u32 fcc, byte *data, int dsz);
int FR2CI_DecodeStructMarkerTWOCC(FR2CI_Image *img, FR2CI_LiteralInfo *str, u16 tcc, byte *css, byte *cse);
int FR2CI_DecodeStructMarkerFOURCC(FR2CI_Image *img, FR2CI_LiteralInfo *str, u32 fcc, byte *css, byte *cse);
int FR2CI_DecodeStructDefField(FR2CI_Image *img, FR2CI_LiteralInfo *str, byte *css, byte *cse);
FR2CI_LiteralInfo *FR2CI_LookupStructName(FR2CI_Image *img, char *name);
int FR2CI_GetStructSigSizeAlign(FR2CI_Image *img, char *sig, int *rsz, int *ral);
int FR2CI_GetSigSizeAlign(FR2CI_Image *img, char *sig, int *rsz, int *ral);
//AHSRC:base/fri_trace.c
FR2CI_Trace *FR2CI_TraceRunGeneric(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric0(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric1(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric2(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric3(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric4(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric5(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric6(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric7(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric8(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric9(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric10(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric11(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric12(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric13(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric14(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric15(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_TraceRunGeneric16(FR2CI_Frame *frm, FR2CI_Trace *tr);
FR2CI_Trace *FR2CI_CreateTrace(FR2CI_Image *img,FR2CI_Opcode **ops, FR2CI_TailOpcode *top, int n_ops);
//AHSRC:base/fri_opbinop.c
FR2CI_Opcode *FR2CI_MakeBinOp(FR2CI_Image *img, int z, int y, int op, int d, int s, int t);
//AHSRC:base/fri_opbinopc.c
FR2CI_Opcode *FR2CI_MakeBinOpCL(FR2CI_Image *img, int z, int y, int op, int d, int s, s64 t);
FR2CI_Opcode *FR2CI_MakeBinOpCD(FR2CI_Image *img, int z, int y, int op, int d, int s, double t);
//AHSRC:base/fri_opcall.c
void FR2CI_OpCall_CopyArgIR(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgLR(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgFR(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgDR(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgPR(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgIA(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgLA(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgFA(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgDA(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgPA(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgIL(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgLL(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgFL(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgDL(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgPL(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgAL(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgIC(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgLC(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgFC(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgDC(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgPC(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgIG(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgLG(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgFG(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgDG(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgPG(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_OpCall_CopyArgAG(FR2CI_Frame *frms, FR2CI_Frame *frmd, FR2CI_ArgOpcode *op);
void FR2CI_DecodeOpCallArgs(FR2CI_Image *img, int na, FR2CI_CallInfo *cinf, byte **rcs);
FR2CI_Trace *FR2CI_Op_CallG(FR2CI_Frame *frm, FR2CI_TailOpcode *op);
FR2CI_Trace *FR2CI_Op_CallPG(FR2CI_Frame *frm, FR2CI_TailOpcode *op);
FR2CI_TailOpcode *FR2CI_DecodeOpCall(FR2CI_Image *img, int gbl, int na, byte **rcs);
FR2CI_TailOpcode *FR2CI_DecodeOpCallP(FR2CI_Image *img, int y, int s, int na, byte **rcs);
FR2CI_Trace *FR2CI_Op_RetV(FR2CI_Frame *frm, FR2CI_TailOpcode *op);
FR2CI_TailOpcode *FR2CI_MakeOpRetV(FR2CI_Image *img);
FR2CI_TailOpcode *FR2CI_MakeOpRet(FR2CI_Image *img, int w, int s);
//AHSRC:base/fri_opcmp.c
FR2CI_Opcode *FR2CI_MakeCmpOp(FR2CI_Image *img, int z, int y, int op, int d, int s, int t);
//AHSRC:base/fri_opcmpc.c
FR2CI_Opcode *FR2CI_MakeCmpOpCL(FR2CI_Image *img, int z, int y, int op, int d, int s, s64 t);
FR2CI_Opcode *FR2CI_MakeCmpOpCD(FR2CI_Image *img, int z, int y, int op, int d, int s, double t);
//AHSRC:base/fri_opconv.c
FR2CI_Opcode *FR2CI_MakeOpConv(FR2CI_Image *img, int z, int y, int d, int s);
FR2CI_Opcode *FR2CI_MakeOpConvI(FR2CI_Image *img, int z, int y, int d, int s);
FR2CI_Opcode *FR2CI_MakeOpConvL(FR2CI_Image *img, int z, int y, int d, int s);
//AHSRC:base/fri_opjcmp.c
FR2CI_TailOpcode *FR2CI_MakeJCmpOp(FR2CI_Image *img, int z, int y, int op, int s, int t, byte *ip);
FR2CI_TailOpcode *FR2CI_MakeJCmpOpLC(FR2CI_Image *img, int z, int y, int op, int s, s64 v, byte *ip);
FR2CI_TailOpcode *FR2CI_MakeJCmpOpDC(FR2CI_Image *img, int z, int y, int op, int s, double v, byte *ip);
FR2CI_Trace *FR2CI_Op_JmpAl(FR2CI_Frame *frm, FR2CI_TailOpcode *op);
FR2CI_Trace *FR2CI_Op_JmpNv(FR2CI_Frame *frm, FR2CI_TailOpcode *op);
FR2CI_TailOpcode *FR2CI_MakeOpJmp(FR2CI_Image *img, byte *ip);
FR2CI_TailOpcode *FR2CI_MakeOpJmpZ(FR2CI_Image *img, int opc, int op, int s, byte *ip);
//AHSRC:base/fri_oploadindex.c
FR2CI_Opcode *FR2CI_MakeOpLoadIndex(FR2CI_Image *img, int z, int y, int d, int s, int t);
FR2CI_Opcode *FR2CI_MakeOpStoreIndex(FR2CI_Image *img, int z, int y, int d, int s, int t);
FR2CI_Opcode *FR2CI_MakeOpLoadIndexC(FR2CI_Image *img, int z, int y, int d, int s, int imm);
FR2CI_Opcode *FR2CI_MakeOpStoreIndexC(FR2CI_Image *img, int z, int y, int d, int s, int imm);
FR2CI_Opcode *FR2CI_MakeOpLea(FR2CI_Image *img, int z, int y, int d, int s, int t);
FR2CI_Opcode *FR2CI_MakeOpLeaC(FR2CI_Image *img, int z, int y, int d, int s, int imm);
//AHSRC:base/fri_oploadslot.c
FR2CI_Opcode *FR2CI_MakeOpLoadSlot(FR2CI_Image *img, int z, int y, int d, int s, int objid, int fidx);
FR2CI_Opcode *FR2CI_MakeOpStoreSlot(FR2CI_Image *img, int z, int y, int d, int s, int objid, int fidx);
FR2CI_Opcode *FR2CI_MakeOpLoadSlotAddr(FR2CI_Image *img, int z, int y, int d, int s, int objid, int fidx);
FR2CI_Opcode *FR2CI_MakeOpCopyObj(FR2CI_Image *img,int y, int d, int s, int c);
//AHSRC:base/fri_opmisc.c
FR2CI_Opcode *FR2CI_MakeOpLDVar(FR2CI_Image *img, int op, int w, int d, int idx);
FR2CI_Opcode*FR2CI_MakeOpShrMask(FR2CI_Image *img, int op, int y, int d, int s, int shr, int msh);
void FR2CI_Op_Nop(FR2CI_Frame *frm, FR2CI_Opcode *op);
FR2CI_Opcode *FR2CI_MakeOpNop(FR2CI_Image *img);
void FR2CI_Op_InitArr_ClopG(FR2CI_Frame *frm, FR2CI_CleanupOpcode *op);
void FR2CI_Op_InitArrG(FR2CI_Frame *frm, FR2CI_Opcode *op);
FR2CI_Opcode *FR2CI_MakeOpInitArr(FR2CI_Image *img,int z, int d, int c);
void FR2CI_Op_InitObj_ClopGR(FR2CI_Frame *frm, FR2CI_CleanupOpcode *op);
void FR2CI_Op_InitObj_ClopGA(FR2CI_Frame *frm, FR2CI_CleanupOpcode *op);
void FR2CI_Op_InitObj_ClopGL(FR2CI_Frame *frm, FR2CI_CleanupOpcode *op);
void FR2CI_Op_InitObjGR(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_InitObjGA(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_InitObjGL(FR2CI_Frame *frm, FR2CI_Opcode *op);
FR2CI_Opcode *FR2CI_MakeOpInitObj(FR2CI_Image *img,int w, int d, int c);
void FR2CI_Op_DropObjGR(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_DropObjGA(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_DropObjGL(FR2CI_Frame *frm, FR2CI_Opcode *op);
FR2CI_Opcode *FR2CI_MakeOpDropObj(FR2CI_Image *img,int w, int d, int c);
void FR2CI_Op_SizeofGR(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_SizeofGA(FR2CI_Frame *frm, FR2CI_Opcode *op);
void FR2CI_Op_SizeofGL(FR2CI_Frame *frm, FR2CI_Opcode *op);
FR2CI_Opcode *FR2CI_MakeOpSizeOf(FR2CI_Image *img,int y, int d, int c);
FR2CI_Opcode *FR2CI_MakeOpOffsetOf(FR2CI_Image *img,int y, int d, int c, int idx);
//AHSRC:base/fri_opunop.c
FR2CI_Opcode *FR2CI_MakeUnOp(FR2CI_Image *img, int z, int y, int op, int d, int s);
//AHSRC:base/fri_opunopc.c
FR2CI_Opcode *FR2CI_MakeUnOpCL(FR2CI_Image *img, int z, int y, int op, int d, s64 s);
FR2CI_Opcode *FR2CI_MakeUnOpCD(FR2CI_Image *img, int z, int y, int op, int d, f64 s);
//AHSRC:base/fri_natfcn_w32.c
int FR2CI_FFI_GetModuleListOS(char **buf, int max);
char **FR2CI_FFI_GetEnvironOS();
void FR2CI_FFI_ProbeTst(byte *buf, int sz);
void FR2CI_FFI_UpdateDllsOS(void *hmod);
int FR2CI_FFI_InitDllsOS();
int FR2CI_FFI_LoadDynamicOS(char *name);
void *FR2CI_FFI_LoadModuleFileDataOS(char *name, int *rsz);
void *FR2CI_FFI_LoadModuleWadDataOS(char *name, int *rsz);
void FR2CI_FFI_FreeModuleDataOS(void *buf);
void FR2CI_FFI_UpdateProxyOS(char *name, void *ptr);
void *FR2CI_FFI_LookupLabelOS_1(char *name);
void *FR2CI_FFI_LookupLabelOS_2(char *name, int *rfl);
void *FR2CI_FFI_LookupLabelOS(char *name);
int FR2CI_FFI_InitDbgHelpOS();
char *FR2CI_FFI_LookupAddrNameOS(void *addr, void **addr2);
int FR2CI_FFI_ProcessEXE(char *name);
//AHSRC:base/fri_natfcn_lnx.c
int FR2CI_FFI_InitDllsOS();
int FR2CI_FFI_GetModuleListOS(char **buf, int max);
char **FR2CI_FFI_GetEnvironOS();
char *FR2CI_FFI_LookupAddrNameOS(void *addr, void **addr2);
int FR2CI_FFI_LoadDynamicOS(char *name);
void FR2CI_FFI_UpdateProxyOS(char *name, void *ptr);
void *FR2CI_FFI_LookupLabelOS(char *name);
int FR2CI_FFI_ProcessEXE(char *name);
void *FR2CI_FFI_LoadFileRawOS(char *name, int *rsz);
void *FR2CI_FFI_LoadModuleFileDataOS(char *name, int *rsz);
void *FR2CI_FFI_LoadModuleWadDataOS(char *name, int *rsz);
void FR2CI_FFI_FreeModuleDataOS(void *buf);
//AHSRC:frbcgl/frgl_input.c
void *frgl_malloc(int sz);
void frgl_free(void *ptr);
char *frgl_strdup(char *str);
void *frgl_talloc(char *ty, int sz);
FRBC2CI_API void *FRGL_GetState(void);
FRBC2CI_API void FRGL_SetupFrame(void);
FRBC2CI_API void FRGL_SetupMain(void);
FRBC2CI_API void FRGL_StartMain(void);
FRBC2CI_API void FRGL_FinishMain(void);
FRBC2CI_API void FRGL_FinishFrame(void);
FRBC2CI_API int FRGL_AddKeyHandler(int (*fcn)(int key, int down));
FRBC2CI_API int FRGL_KeyDown(int key);
FRBC2CI_API int FRGL_GetKeyMap(byte *map);
FRBC2CI_API int GfxDev_Key_Event(int key, int down);
FRBC2CI_API short *FRGL_GetKeybuf();
FRBC2CI_API int FRGL_TimeMS();
FRBC2CI_API int FRGL_DeltaMS(int *l);
FRBC2CI_API void FRGL_RegisterShutdown(void (*fcn)());
FRBC2CI_API void FRGL_Shutdown();
//AHSRC:frbcgl/w32_glw.c
void gfxdrv_lock();
void gfxdrv_unlock();
void gfxdrv_sleep(int ms);
FRBC2CI_API void GfxDrv_GetWindowSize(int *xs, int *ys);
FRBC2CI_API void GfxDrv_GetWindowTexSize(int *xs, int *ys);
FRBC2CI_API void GfxDrv_GetWindowMaxSize(int *xs, int *ys);
FRBC2CI_API void GfxDrv_GetWindowMaxTexSize(int *xs, int *ys);
FRBC2CI_API bool GfxDrv_WindowIsActiveP(void);
FRBC2CI_API bool GfxDrv_WindowIsFullActiveP(void);
FRBC2CI_API bool GfxDrv_WindowIsFullscreenP(void);
FRBC2CI_API void GfxDrv_BeginDrawing();
FRBC2CI_API void GfxDrv_KeyEvent(int key, int down);
FRBC2CI_API void GfxDrv_EndDrawing(void);
void GfxDrv_V_HandleMessages();
int GfxDrv_V_SetWindowedMode();
int GfxDrv_V_GetDesktopSize();
int GfxDrv_V_SetFullscreenMode();
void GfxDrv_UpdateMode();
int GfxDrv_V_SetupWindow();
void GfxDrv_InitGL();
void GfxDrv_InitGL2();
FRBC2CI_API void GfxDrv_Shutdown();
int GfxDrv_MapKey(int key);
void GfxDrv_AppActivate(bool active, bool minimized);
FRBC2CI_API void GfxDrv_SetDefaults(char *label, int width, int height);
FRBC2CI_API void GfxDrv_SetDefaultFullscreen(int fs);
FRBC2CI_API void GfxDrv_SetFullscreenResolution(int width, int height);
FRBC2CI_API int GfxDrv_SetupMainDC();
FRBC2CI_API int GfxDrv_Start();
FRBC2CI_API int GfxDrv_SetupThreadShareLists();
FRBC2CI_API int GfxDrv_TeardownThreadShareLists();
FRBC2CI_API int GfxDrv_Init(void *hInstance, int nCmdShow, int *rkill);
FRBC2CI_API int GfxDrv_SetInstance(void *hInstance, int nCmdShow);
FRBC2CI_API int GfxDrv_SetKill(int *rkill);
//AHSRC:frbcgl/w32_mouse.c
FRBC2CI_API int GfxDrv_MouseGetRelPos(int *dx, int *dy, int *mb);
FRBC2CI_API int GfxDrv_MouseGetPos(int *mx, int *my, int *mb);
FRBC2CI_API int GfxDrv_MouseSetPos(int mx, int my);
//AHSRC:frbcgl/w32_sound.c
FRBC2CI_API int SoundDev_DeInit();
FRBC2CI_API int SoundDev_Init();
FRBC2CI_API int SoundDev_GetDMAPos();
FRBC2CI_API void SoundDev_Submit();
FRBC2CI_API int SoundDev_PaintSamples(short *buffer, int cnt);
FRBC2CI_API int SoundDev_WriteSamples(short *buffer, int cnt);
