//AHSRC:cparse/cparse_token.c
int BGBCP_GetLinenum();
char *BGBCP_GetFilename();
int BGBCP_CalcLinenum(char *se);
int BGBCP_SetLinenum(char *fname, char *base, int num);
int BGBCP_PushLinenum();
int BGBCP_PopLinenum();
int BGBCP_SkimLinenum(char *s, char **rfn, int *rln);
char *BGBCP_GetLastFileName();
int BGBCP_GetLastLineNumber();
char *BGBCP_EatWhiteOnly(char *s);
char *BGBCP_EatWhiteOnly2(char *s);
char *BGBCP_EatWhite(char *s);
int BGBCP_IsWhiteOnly(char *s);
int BGBCP_IsLineBreak(char *se);
int BGBCP_OpChar(int c);
int BGBCP_PeekChar(char **str);
int BGBCP_ParseChar(char **str);
int BGBCP_EmitChar(char **str, int j);
int BGBCP_NameInitChar(int c);
int BGBCP_NameChar(int c);
char *BGBCP_TokenI(char *s, char *b, int *ty, int lang, int sz);
char *BGBCP_Token(char *s, char *b, int *ty);
void BGBCP_FlushToken(char *s);
char *BGBCP_Token(char *s, char *b, int *ty);
void BGBCP_FlushToken(char *s);
char *BGBCP_TokenGen(char *s, char *b, int *ty);
char *BGBCP_TokenLang(char *s, char *b, int *ty, int lang);
char *BGBCP_TokenCtx(BGBCP_ParseState *ctx, char *s, char *b, int *ty);
char *BGBCP_ReadToken(BGBCP_ParseState *ctx, char **str, int *ty);
//AHSRC:cparse/cparse_misc.c
BCCX_Node *BGBCP_FunArgs(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_GenArgs(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ModuleBuffer(char *name, char *modname, char *buf);
int BGBCP_LangForName(char *name);
char *BGBCP_NameForLang(int lang);
int BGBCP_ArchForName(char *name);
char *BGBCP_NameForArch(int arch);
BCCX_Node *BGBCP_ModuleBuffer(char *name, char *modname, char *buf);
//AHSRC:cparse/cparse_type.c
BCCX_Node *BGBCP_LookupStructI(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_LookupStructI(BGBCP_ParseState *ctx, char *name);
int BGBCP_HashTypeNameI(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_LookupTypeI(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_LookupStruct(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_LookupTypeI(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_LookupType(BGBCP_ParseState *ctx, char *name);
int BGBCP_HandleTypedef(BGBCP_ParseState *ctx, BCCX_Node *n);
BCCX_Node *BGBCP_GetStruct(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_GetUnion(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_GetEnum(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBCP_GetStructJ(BGBCP_ParseState *ctx, char *name, int ty);
int BGBCP_CheckTypeName(BGBCP_ParseState *ctx, char *name);
int BGBCP_DefTypeFlag(BGBCP_ParseState *ctx, char *tag);
BCCX_Node *BGBCP_DefClassC(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_DeclAttributeC(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_DefTypeC(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_DefClassJ(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_DefTypeJ(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_DefType(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_EnumVarsList(BGBCP_ParseState *ctx, char **str);
//AHSRC:cparse/cparse_def.c
BCCX_Node *BGBCP_VarsList(BGBCP_ParseState *ctx, char **str, BCCX_Node *tn);
BCCX_Node *BGBCP_FunVarsList(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_DefName(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_DefName2(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_VarDefinition(BGBCP_ParseState *ctx, char **str, BCCX_Node *tn);
BCCX_Node *BGBCP_ArgDefinition(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_Definition(BGBCP_ParseState *ctx, char **str);
//AHSRC:cparse/cparse_expr2.c
int BGBCP_AddExpression(char *name, BCCX_Node *(*func)(BGBCP_ParseState *ctx, char **s));
BCCX_Node *BGBCP_ParseExpressionName(BGBCP_ParseState *ctx, char *name, char **s);
BCCX_Node *BGBCP_Number(BGBCP_ParseState *ctx, char *str);
BCCX_Node *BGBCP_ExpressionLit(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionPostfix(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionUnary(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionCast(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_BinaryExpr(char *op, BCCX_Node *l, BCCX_Node *r);
BCCX_Node *BGBCP_UnaryExpr(char *op, BCCX_Node *v);
BCCX_Node *BGBCP_IfExpr(BCCX_Node *cond, BCCX_Node *ln, BCCX_Node *rn);
BCCX_Node *BGBCP_ExpressionExp(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionMD(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionAS(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionSHLR(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionRCmp(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionECmp(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionBitAnd(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionBitXor(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionBitOr(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionLop(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionLop2(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionTCond(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionEquals(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ExpressionComma(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_Expression(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_Expression2(BGBCP_ParseState *ctx, char **str);
//AHSRC:cparse/cparse_stmt.c
void BGBCP_Warn(char *se, char *str, ...);
void BGBCP_Error(char *se, char *str, ...);
int BGBCP_AddStatement(char *name,BCCX_Node *(*func)(BGBCP_ParseState *ctx, char **s));
BCCX_Node *BGBCP_ParseStatementName(BGBCP_ParseState *ctx, char *name, char **s);
int BGBCP_AddBlockStatement(char *name,BCCX_Node *(*func)(BGBCP_ParseState *ctx, char **s));
BCCX_Node *BGBCP_ParseBlockStatementName(BGBCP_ParseState *ctx, char *name, char **s);
char *BGBCP_EatSemicolon(char *s);
BCCX_Node *BGBCP_Statement(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ParseComment(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_ParseDocComment(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_BlockStatementInner(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_BlockStatement(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_Block(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBCP_BlockStatement2(BGBCP_ParseState *ctx, char **str);
//AHSRC:cparse/preproc.c
int BGBPP_AddIncludePathFront(char *str);
int BGBPP_AddIncludePathBack(char *str);
char *BGBPP_EmitString(char *t, char *s);
char *BGBPP_EmitCharString(char *t, char *s);
void BGBPP_Trigraphs(BGBCP_ParseState *ctx, char *str);
void BGBPP_UniEscape(BGBCP_ParseState *ctx, char *str);
int BGBPP_Error(BGBCP_ParseState *ctx, char *str, ...);
BGBPP_Def *BGBPP_LookupDefine(BGBCP_ParseState *ctx, char *name);
void BGBPP_DeleteDefine(BGBCP_ParseState *ctx, char *name);
void BGBPP_CleanupDefines(BGBCP_ParseState *ctx);
void BGBPP_AddDefine(BGBCP_ParseState *ctx, char *name, char *str);
void BGBPP_AddDefineArgs(BGBCP_ParseState *ctx,char *name, char **args, char *str);
void BGBPP_AddStaticDefine(BGBCP_ParseState *ctx,char *name, char *str);
void BGBPP_AddStaticDefineArgs(BGBCP_ParseState *ctx,char *name, char **args, char *str);
void BGBPP_SendDefines(BGBCP_ParseState *ctx);
char *BGBPP_LoadInclude(BGBCP_ParseState *ctx, char *name, int *rsz);
void BGBPP_Include(BGBCP_ParseState *ctx, char *str);
void BGBPP_Directive2(BGBCP_ParseState *ctx, char *str);
void BGBPP_Directive(BGBCP_ParseState *ctx, char *str);
char *BGBPP_ParseArg(BGBCP_ParseState *ctx, char *s, char *b);
char *BGBPP_PrintName(char *t, char *s);
char *BGBPP_PrintToken(char *t, char *s, int ty);
int BGBPP_Expand(BGBCP_ParseState *ctx, char **src, char **dst, char *op);
int BGBPP_Line(BGBCP_ParseState *ctx, char *str);
int BGBPP_LineDigraph(BGBCP_ParseState *ctx, char *str);
int BGBPP_LinePostFilter(BGBCP_ParseState *ctx, char *str);
char *BGBPP_ParseLine(BGBCP_ParseState *ctx, char *s, char *b);
void BGBPP_BufferLine(BGBCP_ParseState *ctx, char *b);
void BGBPP_Buffer(BGBCP_ParseState *ctx, char *ibuf);
int BGBPP_Filter(BGBCP_ParseState *ctx, char *ibuf, char *obuf);
//AHSRC:jparse/jp_token2.c
int BGBJP_GetLinenum();
char *BGBJP_GetFilename();
int BGBJP_CalcLinenum(char *se);
int BGBJP_SetLinenum(char *fname, char *base, int num);
int BGBJP_PushLinenum();
int BGBJP_PopLinenum();
int BGBJP_SkimLinenum(char *s, char **rfn, int *rln);
char *BGBJP_GetLastFileName();
int BGBJP_GetLastLineNumber();
char *BGBJP_EatWhiteOnly(char *s);
char *BGBJP_EatWhiteOnly2(char *s);
char *BGBJP_EatWhite(char *s);
int BGBJP_IsWhiteOnly(char *s);
int BGBJP_IsLineBreak(char *se);
int BGBJP_OpChar(int c);
int BGBJP_PeekChar(char **str);
int BGBJP_ParseChar(char **str);
int BGBJP_EmitChar(char **str, int j);
int BGBJP_NameChar(int c);
char *BGBJP_Token(char *s, char *b, int *ty);
void BGBJP_FlushToken(char *s);
char *BGBJP_TokenGen(char *s, char *b, int *ty);
//AHSRC:jparse/jp_misc.c
BCCX_Node *BGBJP_FunArgs(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_FunArgs2(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ModuleBuffer(char *name, char *modname, char *buf);
//AHSRC:jparse/jp_type.c
int BGBJP_HashTypeNameI(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBJP_LookupTypeI(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBJP_LookupType(BGBCP_ParseState *ctx, char *name);
int BGBJP_HandleTypedef(BGBCP_ParseState *ctx, BCCX_Node *n);
BCCX_Node *BGBJP_NewStructJ(BGBCP_ParseState *ctx, char *name, int ty);
int BGBJP_CheckTypeName(BGBCP_ParseState *ctx, char *name);
BCCX_Node *BGBJP_EnumVarsList(BGBCP_ParseState *ctx, char **str);
int BGBJP_DefTypeFlag(BGBCP_ParseState *ctx, char *tag);
BCCX_Node *BGBJP_DefClass(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_DeclAttribute(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_DefType(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_FlagsBlock(BGBCP_ParseState *ctx, char **str);
//AHSRC:jparse/jp_def.c
BCCX_Node *BGBJP_VarsList(BGBCP_ParseState *ctx, char **str, BCCX_Node *tn);
BCCX_Node *BGBJP_FunVarsList(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_DefName(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_DefName2(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_VarDefinition(BGBCP_ParseState *ctx, char **str, BCCX_Node *tn, int mfl);
BCCX_Node *BGBJP_ArgDefinition(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_Definition(BGBCP_ParseState *ctx, char **str);
//AHSRC:jparse/jp_tyexpr.c
BCCX_Node *BGBJP_TypeArgExpression(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_TypeArgs(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_TypeExpressionLit(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_TypeExpressionPE(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_TypeExpressionUnary(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_TypeExpressionBinary(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_TypeExpression(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_CastTypeExpression(BGBCP_ParseState *ctx, char **str);
//AHSRC:jparse/jp_expr2.c
int BGBJP_AddExpression(char *name, BCCX_Node *(*func)(BGBCP_ParseState *ctx, char **s));
BCCX_Node *BGBJP_ParseExpressionName(BGBCP_ParseState *ctx, char *name, char **s);
BCCX_Node *BGBJP_Number(BGBCP_ParseState *ctx, char *str);
BCCX_Node *BGBJP_ExpressionFunction(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionLit(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionPostfix(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionUnary(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionCast(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_BinaryExpr(char *op, BCCX_Node *l, BCCX_Node *r);
BCCX_Node *BGBJP_ExpressionExp(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionMD(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionAS(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionSHLR(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionRCmp(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionECmp(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionBitAnd(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionBitXor(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionBitOr(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionLop(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionLop2(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionTCond(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionEquals(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_ExpressionComma(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_Expression(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_Expression2(BGBCP_ParseState *ctx, char **str);
//AHSRC:jparse/jp_stmt.c
void BGBJP_Warn(char *se, char *str, ...);
void BGBJP_Error(char *se, char *str, ...);
int BGBJP_AddStatement(char *name,BCCX_Node *(*func)(BGBCP_ParseState *ctx, char **s));
BCCX_Node *BGBJP_ParseStatementName(BGBCP_ParseState *ctx, char *name, char **s);
int BGBJP_AddBlockStatement(char *name,BCCX_Node *(*func)(BGBCP_ParseState *ctx, char **s));
BCCX_Node *BGBJP_ParseBlockStatementName(BGBCP_ParseState *ctx, char *name, char **s);
char *BGBJP_EatSemicolon(char *s);
BCCX_Node *BGBJP_Statement(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_BlockStatementInner(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_BlockStatement(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_Block(BGBCP_ParseState *ctx, char **str);
BCCX_Node *BGBJP_BlockStatement2(BGBCP_ParseState *ctx, char **str);
//AHSRC:cc/cc_compile.c
void BGBCC_Warn(char *str, ...);
void BGBCC_Error(char *str, ...);
char *BGBCC_GenSym();
char *BGBCC_GenSym2();
void bgbcc_puts(BGBCC_State *ctx, char *str);
void bgbcc_print(BGBCC_State *ctx, char *str, ...);
int BGBCC_CompileSwitch(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileStatement(BGBCC_State *ctx, BCCX_Node *l);
char *BGBCC_VarTypeString_FlattenExpr(BGBCC_State *ctx,char *dst, BCCX_Node *l, int fl);
char *BGBCC_VarTypeString_FlattenName(BGBCC_State *ctx,char *t, char *s, int i);
int BGBCC_VarTypeString_ModifierChar(BGBCC_State *ctx, int i);
char *BGBCC_VarTypeString_FlattenModifiers(BGBCC_State *ctx,char *t, int fl);
char *BGBCC_VarTypeString_FlattenModifiers2(BGBCC_State *ctx,char *t, int fl);
char *BGBCC_VarTypeString(BGBCC_State *ctx, BCCX_Node *ty);
char *BGBCC_VarTypeFlagsString(BGBCC_State *ctx, BCCX_Node *ty);
void BGBCC_EmitVar(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_EmitVar2(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_EmitVar3(BGBCC_State *ctx, char *name, char *ty);
void BGBCC_EmitVarProperty(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileVarProperty(BGBCC_State *ctx, BCCX_Node *l);
int BGBCC_CompileVarDummyP(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileVarStatement(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileVarStatement2(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_CompileBlock(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args, BCCX_Node *body);
char *BGBCC_GenProtoSig(BGBCC_State *ctx,BCCX_Node *type, BCCX_Node *args);
void BGBCC_EmitSigProto(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
BCCX_Node *BGBCC_CompileProto(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
void BGBCC_CompileStruct(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileUnion(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileClass(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileEnum(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_CompileSProto(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_GetNodeAttribute(BGBCC_State *ctx,BCCX_Node *l, char *name);
char *BGBCC_GetNodeAttributeString(BGBCC_State *ctx,BCCX_Node *l, char *name);
void BGBCC_CompileTypedef(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileStructs(BGBCC_State *ctx);
void BGBCC_EmitVarValue(BGBCC_State *ctx, BCCX_Node *v);
void BGBCC_EmitVarValueR(BGBCC_State *ctx, BCCX_Node *v);
void BGBCC_EmitVarValueR2(BGBCC_State *ctx, BCCX_Node *v);
char *BGBCC_QualifyNameNS(BGBCC_State *ctx, char *name);
void BGBCC_EmitTopArray(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_EmitTopVar(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_CompileTopStatement(BGBCC_State *ctx, BCCX_Node *l);
char *BGBCC_CompileModule(char *name, BCCX_Node *l);
//AHSRC:cc/cc_expr.c
char *BGBCC_CIfy(char *s);
void BGBCC_CompileAssign(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileExprList(BGBCC_State *ctx, BCCX_Node *lst);
void BGBCC_CompileExprListReverse(BGBCC_State *ctx, BCCX_Node *lst);
void BGBCC_CompileArgsList(BGBCC_State *ctx, BCCX_Node *lst);
void BGBCC_CompileFuncall(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileForm(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileExprT(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileExpr(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_CompileExprTail(BGBCC_State *ctx, BCCX_Node *l);
//AHSRC:cc/cc_index.c
void BGBCC_EmitLabel(BGBCC_State *ctx, char *name);
void BGBCC_CompileBreak(BGBCC_State *ctx);
void BGBCC_CompileContinue(BGBCC_State *ctx);
void BGBCC_CompileBreakFalse(BGBCC_State *ctx);
void BGBCC_CompileBreakTrue(BGBCC_State *ctx);
void BGBCC_CompileContinueFalse(BGBCC_State *ctx);
void BGBCC_CompileContinueTrue(BGBCC_State *ctx);
void BGBCC_CompileJmp(BGBCC_State *ctx, char *s);
void BGBCC_CompileJmpFalse(BGBCC_State *ctx, char *s);
void BGBCC_CompileJmpTrue(BGBCC_State *ctx, char *s);
void BGBCC_CompileJmpCond(BGBCC_State *ctx, char *op, char *s);
void BGBCC_CompileJCO(BGBCC_State *ctx, char *op,BCCX_Node *ln, BCCX_Node *rn, char *s);
void BGBCC_CompileJCT(BGBCC_State *ctx, BCCX_Node *l, char *s);
void BGBCC_CompileJCF(BGBCC_State *ctx, BCCX_Node *l, char *s);
int BGBCC_TryGetSizeofType(BGBCC_State *ctx, BCCX_Node *ty);
//AHSRC:cc/cc_reduce.c
int BGBCC_IsUnaryP(BCCX_Node *l, char *op);
int BGBCC_IsBinaryP(BCCX_Node *l, char *op);
int BGBCC_BoolExpr(BGBCC_State *ctx, BCCX_Node *l);
int BGBCC_IsExpr(BCCX_Node *l);
int BGBCC_BoolExpr(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_WrapIntSuf(s64 i, char *suf);
BCCX_Node *BGBCC_WrapRealSuf(double f, char *suf);
BCCX_Node *BGBCC_WrapInt(s64 i);
BCCX_Node *BGBCC_WrapReal(double f);
int BGBCC_IsIntP(BGBCC_State *ctx, BCCX_Node *l);
int BGBCC_IsRealP(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_Boolify(BGBCC_State *ctx, BCCX_Node *l);
char *BGBCC_BinaryTySuf(BGBCC_State *ctx, char *op,BCCX_Node *ln, BCCX_Node *rn);
BCCX_Node *BGBCC_ReduceForm(BGBCC_State *ctx, BCCX_Node *l);
int BGBCC_SetLine(BGBCC_State *ctx, BCCX_Node *l,char *fn, int ln);
BCCX_Node *BGBCC_ReduceStatementForm(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_ReduceExpr(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_ReduceStatement(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_InferTypeBase(BCCX_Node *l);
int BGBCC_InferIsIntP(BCCX_Node *t);
int BGBCC_InferIsLongP(BCCX_Node *t);
int BGBCC_InferIsFloatP(BCCX_Node *t);
int BGBCC_InferIsDoubleP(BCCX_Node *t);
int BGBCC_InferIsNumP(BCCX_Node *t);
BCCX_Node *BGBCC_InferIsInt(BCCX_Node *t);
BCCX_Node *BGBCC_InferIsLong(BCCX_Node *t);
BCCX_Node *BGBCC_InferIsNum(BCCX_Node *t);
BCCX_Node *BGBCC_InferForm(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_InferExpr(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_InferExprClean(BGBCC_State *ctx, BCCX_Node *l, int *cp);
int BGBCC_GuessCloseForm(BGBCC_State *ctx, BCCX_Node *l);
int BGBCC_GuessCloseExpr(BGBCC_State *ctx, BCCX_Node *l);
int BGBCC_GuessCloseBlock(BGBCC_State *ctx, BCCX_Node *l);
//AHSRC:cc/ccm_compile.c
void BGBCC_MetaCompileStatement(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_MetaEmitVar(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_MetaEmitVar2(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_MetaCompileVarStatement(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_MetaCompileBlock(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args, BCCX_Node *body);
char *BGBCC_GenProtoSig(BGBCC_State *ctx,BCCX_Node *type, BCCX_Node *args);
void BGBCC_MetaEmitSigProto(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
BCCX_Node *BGBCC_MetaCompileProto(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
void BGBCC_MetaCompileStruct(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_MetaCompileUnion(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_MetaCompileEnum(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_MetaCompileSProto(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_MetaCompileTypedef(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_MetaCompileStructs(BGBCC_State *ctx);
void BGBCC_MetaEmitVarValue(BGBCC_State *ctx, BCCX_Node *v);
void BGBCC_MetaEmitVarValueR(BGBCC_State *ctx, BCCX_Node *v);
void BGBCC_MetaEmitTopArray(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_MetaEmitTopVar(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_MetaCompileTopStatement(BGBCC_State *ctx, BCCX_Node *l);
char *BGBCC_MetaCompileModule(char *name, BCCX_Node *l);
//AHSRC:cc/cc_gast.c
BCCX_Node *BGBCC_GAstCompileStatementList(BGBCC_State *ctx, char *tag,BCCX_Node *lst);
BCCX_Node *BGBCC_GAstCompileStatementBody(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_GAstCompileStatement(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_GAstCompileType(BGBCC_State *ctx, BCCX_Node *ty);
BCCX_Node *BGBCC_GAstCompileVar(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_GAstCompileBlock(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args, BCCX_Node *body);
BCCX_Node *BGBCC_GAstCompileProto(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
BCCX_Node *BGBCC_GAstCompileStruct(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_GAstCompileUnion(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_GAstCompileSProto(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_GAstCompileTypedef(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_GAstCompileStructs(BGBCC_State *ctx);
BCCX_Node *BGBCC_GAstCompileTopStatement(BGBCC_State *ctx, BCCX_Node *l);
byte *BGBCC_GAstCompileModule(char *name, BCCX_Node *l, int *rsz);
//AHSRC:cc/bs2cc_compile.c
int BGBCC_BS2IL_CompileSwitch(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileStatement(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_EmitVar(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_BS2IL_EmitVar2(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_BS2IL_EmitVar3(BGBCC_State *ctx, char *name, char *ty);
void BGBCC_BS2IL_EmitVar4(BGBCC_State *ctx, char *name, BCCX_Node *ty);
void BGBCC_BS2IL_EmitVarProperty(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileVarProperty(BGBCC_State *ctx, BCCX_Node *l);
int BGBCC_BS2IL_CompileVarDummyP(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileVarStatement(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileVarStatement2(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_BS2IL_CompileBlock(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args, BCCX_Node *body);
void BGBCC_BS2IL_EmitSigProto(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
BCCX_Node *BGBCC_BS2IL_CompileProto(BGBCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
void BGBCC_BS2IL_CompileStruct(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileUnion(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileClass(BGBCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_BS2IL_CompileSProto(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileTypedef(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileStructs(BGBCC_State *ctx);
void BGBCC_BS2IL_EmitVarValue(BGBCC_State *ctx, BCCX_Node *v);
void BGBCC_BS2IL_EmitVarValueR(BGBCC_State *ctx, BCCX_Node *v);
void BGBCC_BS2IL_EmitVarValueR2(BGBCC_State *ctx, BCCX_Node *v);
void BGBCC_BS2IL_EmitTopArray(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_BS2IL_EmitTopVar(BGBCC_State *ctx, char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_BS2IL_CompileTopStatement(BGBCC_State *ctx, BCCX_Node *l);
char *BGBCC_BS2IL_CompileModule(char *name, BCCX_Node *l);
//AHSRC:cc/bs2cc_expr.c
void BGBCC_BS2IL_CompileAssign(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileExprList(BGBCC_State *ctx, BCCX_Node *lst);
void BGBCC_BS2IL_CompileExprListReverse(BGBCC_State *ctx, BCCX_Node *lst);
void BGBCC_BS2IL_CompileArgsList(BGBCC_State *ctx, BCCX_Node *lst);
void BGBCC_BS2IL_CompileFuncall(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileForm(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileExprT(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileExpr(BGBCC_State *ctx, BCCX_Node *l);
void BGBCC_BS2IL_CompileExprTail(BGBCC_State *ctx, BCCX_Node *l);
//AHSRC:cc/bs2cc_index.c
void BGBCC_BS2IL_EmitLabel(BGBCC_State *ctx, char *name);
void BGBCC_BS2IL_CompileBreak(BGBCC_State *ctx);
void BGBCC_BS2IL_CompileContinue(BGBCC_State *ctx);
void BGBCC_BS2IL_CompileBreakFalse(BGBCC_State *ctx);
void BGBCC_BS2IL_CompileBreakTrue(BGBCC_State *ctx);
void BGBCC_BS2IL_CompileContinueFalse(BGBCC_State *ctx);
void BGBCC_BS2IL_CompileContinueTrue(BGBCC_State *ctx);
void BGBCC_BS2IL_CompileJmp(BGBCC_State *ctx, char *s);
void BGBCC_BS2IL_CompileJmpFalse(BGBCC_State *ctx, char *s);
void BGBCC_BS2IL_CompileJmpTrue(BGBCC_State *ctx, char *s);
void BGBCC_BS2IL_CompileJmpCond(BGBCC_State *ctx, char *op, char *s);
void BGBCC_BS2IL_CompileJCO(BGBCC_State *ctx, char *op,BCCX_Node *ln, BCCX_Node *rn, char *s);
void BGBCC_BS2IL_CompileJCT(BGBCC_State *ctx, BCCX_Node *l, char *s);
void BGBCC_BS2IL_CompileJCF(BGBCC_State *ctx, BCCX_Node *l, char *s);
//AHSRC:frcc/frbc_call.c
frbc_status BGBCC_FrBC_EmitCallOp(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src, int na);
frbc_status BGBCC_FrBC_EmitCallCsrvOp(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src);
frbc_status BGBCC_FrBC_EmitCallArg(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_status BGBCC_FrBC_EmitCallRetDefault(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_EmitCallRetV(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_EmitCallRetOp(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register src);
//AHSRC:frcc/frbc_const.c
int BGBCC_FrBC_CheckExpandLvt4(BGBCC_FrCC_State *ctx);
int BGBCC_FrBC_CheckExpandLvt8(BGBCC_FrCC_State *ctx);
int BGBCC_FrBC_IndexLitU32(BGBCC_FrCC_State *ctx, u32 val);
int BGBCC_FrBC_IndexLitU64(BGBCC_FrCC_State *ctx, u32 val);
int BGBCC_FrBC_IndexLitS32(BGBCC_FrCC_State *ctx, s32 val);
int BGBCC_FrBC_IndexLitF32(BGBCC_FrCC_State *ctx, float val);
int BGBCC_FrBC_IndexLitS64(BGBCC_FrCC_State *ctx, s64 val);
int BGBCC_FrBC_IndexLitF64(BGBCC_FrCC_State *ctx, double val);
int BGBCC_FrBC_LookupString(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_LookupWString(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_IndexString(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_IndexWString(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_IndexCountString(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_FlattenCountStrings(BGBCC_FrCC_State *ctx);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_LookupStruct(BGBCC_FrCC_State *ctx, char *str);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_LookupUnion(BGBCC_FrCC_State *ctx, char *str);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_LookupStructure(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_LookupStructureID(BGBCC_FrCC_State *ctx, char *str);
void BGBCC_FrBC_CheckExpandLiterals(BGBCC_FrCC_State *ctx);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_GetStruct(BGBCC_FrCC_State *ctx, char *str);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_GetUnion(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_GetStructID(BGBCC_FrCC_State *ctx, char *str);
int BGBCC_FrBC_GetUnionID(BGBCC_FrCC_State *ctx, char *str);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_LookupTypedef(BGBCC_FrCC_State *ctx, char *name, char *sig);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_GetTypedef(BGBCC_FrCC_State *ctx, char *name, char *sig);
//AHSRC:frcc/frbc_dbgdisasm.c
int BGBCC_FrBC_DbgDisAsm_CheckMatch(BGBCC_FrCC_State *ctx, byte *css, char *pat);
int BGBCC_FrBC_DbgDisAsm_LookupMatch(BGBCC_FrCC_State *ctx, byte *cs);
int BGBCC_FrBC_DbgDisAsm_GetArgsOpLen(BGBCC_FrCC_State *ctx, byte *css, int na);
int BGBCC_FrBC_DbgDisAsm_GetPatOpLen(BGBCC_FrCC_State *ctx, byte *css, char *pat);
int BGBCC_FrBC_DbgDisAsm_DecodeOpArgsList(BGBCC_FrCC_State *ctx, byte *css, byte **rcs, int na);
int BGBCC_FrBC_DbgDisAsm_DecodeOp(BGBCC_FrCC_State *ctx, byte *css, byte **rcs);
void BGBCC_FrBC_DbgDisAsmFunction(BGBCC_FrCC_State *ctx,BGBCC_FrCC_LiteralInfo *obj);
//AHSRC:frcc/frbc_emit.c
void BGBCC_FrBC_CheckExpandLabel(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_CheckExpandGoto(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_CheckExpandText(BGBCC_FrCC_State *ctx, int sz);
void BGBCC_FrBC_EmitLabel(BGBCC_FrCC_State *ctx, char *name);
void BGBCC_FrBC_EmitGotoAddr16(BGBCC_FrCC_State *ctx, char *name);
void BGBCC_FrBC_EmitGotoAddr32(BGBCC_FrCC_State *ctx, char *name);
void BGBCC_FrBC_EmitRelocTag(BGBCC_FrCC_State *ctx, int tag);
void BGBCC_FrBC_EmitLitInt12(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitLitLong12(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitLitFloat12(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitLitDouble12(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitLitZ12(BGBCC_FrCC_State *ctx, int z);
void BGBCC_FrBC_EmitRelocLiteral12(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitRelocGlobal12(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitRelocLiteral16(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitRelocGlobal16(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitRelocLiteral24(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitRelocGlobal24(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitMarkEndTrace(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitMarkLastOpRet(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_EmitByte(BGBCC_FrCC_State *ctx, int val);
void BGBCC_FrBC_EmitWord(BGBCC_FrCC_State *ctx, int val);
void BGBCC_FrBC_EmitWord24(BGBCC_FrCC_State *ctx, int val);
void BGBCC_FrBC_EmitDWord(BGBCC_FrCC_State *ctx, int val);
frbc_status BGBCC_FrBC_EmitOpcode(BGBCC_FrCC_State *ctx, int val);
frbc_status BGBCC_FrBC_EmitMov(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src);
frbc_status BGBCC_FrBC_EmitConv(BGBCC_FrCC_State *ctx, frbc_type dtype, frbc_type stype, frbc_register dst, frbc_register src);
frbc_status BGBCC_FrBC_EmitUnaryOp(BGBCC_FrCC_State *ctx, frbc_type type, int opr, frbc_register dst, frbc_register src);
frbc_status BGBCC_FrBC_EmitBinaryOp(BGBCC_FrCC_State *ctx, frbc_type type, int opr, frbc_register dst, frbc_register srca, frbc_register srcb);
frbc_status BGBCC_FrBC_EmitCompareOp(BGBCC_FrCC_State *ctx, frbc_type type, int opr, frbc_register dst, frbc_register srca, frbc_register srcb);
frbc_status BGBCC_FrBC_EmitJump(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_EmitJumpRegZero(BGBCC_FrCC_State *ctx, frbc_type type, int opr, frbc_register src, char *name);
frbc_status BGBCC_FrBC_EmitJumpRegCmp(BGBCC_FrCC_State *ctx, frbc_type type, int opr, frbc_register srca, frbc_register srcb, char *name);
//AHSRC:frcc/frbc_global.c
void BGBCC_FrBC_CheckExpandGlobals(BGBCC_FrCC_State *ctx);
BGBCC_FrCC_RegisterInfo *BGBCC_FrBC_LookupGlobal(BGBCC_FrCC_State *ctx, char *name);
BGBCC_FrCC_RegisterInfo *BGBCC_FrBC_GetGlobal(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_EmitLoadGlobal(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src);
frbc_status BGBCC_FrBC_EmitStoreGlobal(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src);
//AHSRC:frcc/frbc_image.c
void BGBCC_FrBC_StubErrorLLn(BGBCC_FrCC_State *ctx,char *file, int line);
void BGBCC_FrBC_StubWarnLLn(BGBCC_FrCC_State *ctx,char *file, int line);
void BGBCC_FrBC_StubNoteLLn(BGBCC_FrCC_State *ctx,char *file, int line);
void BGBCC_FrBC_TagErrorLLn(BGBCC_FrCC_State *ctx, int tag,char *file, int line);
void BGBCC_FrBC_TagWarnLLn(BGBCC_FrCC_State *ctx, int tag,char *file, int line);
void BGBCC_FrBC_TagNoteLLn(BGBCC_FrCC_State *ctx, int tag,char *file, int line);
void BGBCC_FrBC_AddGlobalDecl(BGBCC_FrCC_State *ctx,BGBCC_FrCC_RegisterInfo *decl);
void BGBCC_FrBC_AddFrameArg(BGBCC_FrCC_State *ctx,BGBCC_FrCC_RegisterInfo *frame, BGBCC_FrCC_RegisterInfo *decl);
void BGBCC_FrBC_AddFrameLocal(BGBCC_FrCC_State *ctx,BGBCC_FrCC_RegisterInfo *frame, BGBCC_FrCC_RegisterInfo *decl);
void BGBCC_FrBC_AddFrameField(BGBCC_FrCC_State *ctx,BGBCC_FrCC_RegisterInfo *frame, BGBCC_FrCC_RegisterInfo *decl);
void BGBCC_FrBC_AddLiteral(BGBCC_FrCC_State *ctx,BGBCC_FrCC_LiteralInfo *obj);
void BGBCC_FrBC_Begin(BGBCC_FrCC_State *ctx, int tag);
void BGBCC_FrBC_BeginName(BGBCC_FrCC_State *ctx, int tag, char *name);
int BGBCC_FrBC_LookupCurFunctionLabel(BGBCC_FrCC_State *ctx, char *name);
void BGBCC_FrBC_EndFunction(BGBCC_FrCC_State *ctx,BGBCC_FrCC_LiteralInfo *obj);
void BGBCC_FrBC_End(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_AttribStr(BGBCC_FrCC_State *ctx, int attr, char *str);
void BGBCC_FrBC_AttribInt(BGBCC_FrCC_State *ctx, int attr, int val);
void BGBCC_FrBC_AttribLong(BGBCC_FrCC_State *ctx, int attr, s64 val);
void BGBCC_FrBC_Marker(BGBCC_FrCC_State *ctx, int tag);
void BGBCC_FrBC_ListAddLiteral(BGBCC_FrCC_State *ctx, BGBCC_FrCC_LiteralInfo *list, frbc_register val);
void BGBCC_FrBC_LiteralInt(BGBCC_FrCC_State *ctx, int attr, s32 val);
void BGBCC_FrBC_LiteralLong(BGBCC_FrCC_State *ctx, int attr, s64 val);
void BGBCC_FrBC_LiteralFloat(BGBCC_FrCC_State *ctx, int attr, double val);
void BGBCC_FrBC_LiteralDouble(BGBCC_FrCC_State *ctx, int attr, double val);
void BGBCC_FrBC_LiteralStr(BGBCC_FrCC_State *ctx, int attr, char *str);
void BGBCC_FrBC_LiteralWStr(BGBCC_FrCC_State *ctx, int attr, char *str);
byte *BGBCC_FrBC_EmitBufVLIE(byte *ct, s64 vli);
void BGBCC_FrBC_FlattenImage_EmitGlobalVarDecl(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, BGBCC_FrCC_RegisterInfo *gbl);
void BGBCC_FrBC_FlattenImage_EmitGlobalFuncDecl(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, BGBCC_FrCC_RegisterInfo *gbl);
void BGBCC_FrBC_FlattenImage_EmitGlobalNullDecl(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, BGBCC_FrCC_RegisterInfo *gbl);
void BGBCC_FrBC_FlattenImage_EmitLiteralNullDecl(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, BGBCC_FrCC_LiteralInfo *lit);
void BGBCC_FrBC_FlattenImage_EmitGlobal(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, int gidx);
void BGBCC_FrBC_FlattenImage_EmitStructDefField(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, BGBCC_FrCC_RegisterInfo *gbl);
void BGBCC_FrBC_FlattenImage_EmitStructDef(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, BGBCC_FrCC_LiteralInfo *obj);
void BGBCC_FrBC_FlattenImage_EmitTypeDef(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, BGBCC_FrCC_LiteralInfo *obj);
void BGBCC_FrBC_FlattenImage_EmitLiteral(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct, int idx);
void BGBCC_FrBC_FlattenImage_Globals(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct);
void BGBCC_FrBC_FlattenImage_Literals(BGBCC_FrCC_State *ctx, byte *obuf, int omsz, byte **rct);
void BGBCC_FrBC_PreFlattenImage_Globals(BGBCC_FrCC_State *ctx);
void BGBCC_FrBC_PreFlattenImage_Literals(BGBCC_FrCC_State *ctx);
int BGBCC_FrBC_FlattenImage(BGBCC_FrCC_State *ctx, byte *obuf, int omsz);
//AHSRC:frcc/frbc_pred.c
bool BGBCC_FrBC_IsRegBasicP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegArgBasicP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegLocalBasicP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegBaseP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegBaseExtP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegRegExtP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegArgExtP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegLocalExtP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegGlobalP(BGBCC_FrCC_State *ctx, frbc_register reg);
int BGBCC_FrBC_GetRegID(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_type BGBCC_FrBC_MakeTypeID(BGBCC_FrCC_State *ctx, int id);
frbc_type BGBCC_FrBC_GetRegType(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_type BGBCC_FrBC_GetRegDerefType(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_type BGBCC_FrBC_GetRegReturnType(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_type BGBCC_FrBC_GetRegPointerToType(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmIntP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmLongP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmFloatP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmDoubleP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmStringP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmWStringP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmLiteralP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmInt12P(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImm12P(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
bool BGBCC_FrBC_IsRegImmIntLit12P(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmP(BGBCC_FrCC_State *ctx, frbc_register reg);
bool BGBCC_FrBC_IsRegImmZeroP(BGBCC_FrCC_State *ctx, frbc_register reg);
int BGBCC_FrBC_GetRegImmLit12(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
int BGBCC_FrBC_GetRegImmLit12(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
int BGBCC_FrBC_GetRegImmLit16(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
int BGBCC_FrBC_GetRegImmLit24(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
int BGBCC_FrBC_GetRegImmLitIndex(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
int BGBCC_FrBC_GetRegImmIntValue(BGBCC_FrCC_State *ctx, frbc_register reg);
s64 BGBCC_FrBC_GetRegImmLongValue(BGBCC_FrCC_State *ctx, frbc_register reg);
double BGBCC_FrBC_GetRegImmFloatValue(BGBCC_FrCC_State *ctx, frbc_register reg);
double BGBCC_FrBC_GetRegImmDoubleValue(BGBCC_FrCC_State *ctx, frbc_register reg);
int BGBCC_FrBC_GetRegImm12Value(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
frbc_status BGBCC_FrBC_GetRegForIntValue(BGBCC_FrCC_State *ctx, frbc_register *rreg, s32 val);
frbc_status BGBCC_FrBC_GetRegForLongValue(BGBCC_FrCC_State *ctx, frbc_register *rreg, s64 val);
frbc_status BGBCC_FrBC_GetRegForFloatValue(BGBCC_FrCC_State *ctx, frbc_register *rreg, f32 val);
frbc_status BGBCC_FrBC_GetRegForDoubleValue(BGBCC_FrCC_State *ctx, frbc_register *rreg, f64 val);
frbc_status BGBCC_FrBC_GetRegForStringValue(BGBCC_FrCC_State *ctx, frbc_register *rreg, char *str);
frbc_status BGBCC_FrBC_GetRegForWStringValue(BGBCC_FrCC_State *ctx, frbc_register *rreg, char *str);
frbc_status BGBCC_FrBC_GetRegForLiteralValue(BGBCC_FrCC_State *ctx, frbc_register *rreg, s32 val);
int BGBCC_FrBC_GetRegOprMode1(BGBCC_FrCC_State *ctx, frbc_register reg);
int BGBCC_FrBC_GetRegOprMode2(BGBCC_FrCC_State *ctx, frbc_register rega, frbc_register regb);
int BGBCC_FrBC_GetRegOprMode3(BGBCC_FrCC_State *ctx, frbc_register dst, frbc_register rega, frbc_register regb);
int BGBCC_FrBC_GetRegOprModeW(BGBCC_FrCC_State *ctx, frbc_register reg, frbc_type type);
int BGBCC_FrBC_GetTypeOperationZ(BGBCC_FrCC_State *ctx, frbc_type ty);
//AHSRC:frcc/frbc_ptrops.c
frbc_status BGBCC_FrBC_EmitLoadIndexImm(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src, int idx);
frbc_status BGBCC_FrBC_EmitStoreIndexImm(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src, int idx);
frbc_status BGBCC_FrBC_EmitLoadIndex(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register srca, frbc_register srcb);
frbc_status BGBCC_FrBC_EmitStoreIndex(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register srca, frbc_register srcb);
frbc_status BGBCC_FrBC_EmitLeaImm(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src, int idx);
frbc_status BGBCC_FrBC_EmitLea(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register srca, frbc_register srcb);
frbc_status BGBCC_FrBC_EmitLdaVar(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src);
frbc_status BGBCC_FrBC_EmitSizeofVar(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst);
//AHSRC:frcc/frbc_register.c
BGBCC_FrCC_RegisterInfo *BGBCC_FrBC_AllocRegisterInfo(BGBCC_FrCC_State *ctx);
bool BGBCC_FrBC_FreeRegisterInfo(BGBCC_FrCC_State *ctx,BGBCC_FrCC_RegisterInfo *rinf);
frbc_status BGBCC_FrBC_RegisterAllocTemporaryLLn(BGBCC_FrCC_State *ctx, frbc_type bty, frbc_register *rtreg, char *fn, int ln);
frbc_status BGBCC_FrBC_RegisterAllocTemporaryInt(BGBCC_FrCC_State *ctx, frbc_register *rtreg);
frbc_status BGBCC_FrBC_RegisterAllocTemporaryLong(BGBCC_FrCC_State *ctx, frbc_register *rtreg);
frbc_status BGBCC_FrBC_RegisterAllocTemporaryFloat(BGBCC_FrCC_State *ctx, frbc_register *rtreg);
frbc_status BGBCC_FrBC_RegisterAllocTemporaryDouble(BGBCC_FrCC_State *ctx, frbc_register *rtreg);
frbc_status BGBCC_FrBC_RegisterAllocTemporaryPointer(BGBCC_FrCC_State *ctx, frbc_register *rtreg);
frbc_status BGBCC_FrBC_RegisterCheckRelease(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_status BGBCC_FrBC_RegisterCheckAcquire(BGBCC_FrCC_State *ctx, frbc_register reg);
//AHSRC:frcc/frbc_stack.c
void BGBCC_FrBC_DebugPrintStackLLn(BGBCC_FrCC_State *ctx, char *op, char *file, int line);
frbc_status BGBCC_FrBC_CheckExpandStack(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_PushRegister(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_status BGBCC_FrBC_PopRegister(BGBCC_FrCC_State *ctx,frbc_register *rreg);
frbc_status BGBCC_FrBC_PushURegister(BGBCC_FrCC_State *ctx, frbc_register reg);
frbc_status BGBCC_FrBC_PopURegister(BGBCC_FrCC_State *ctx,frbc_register *rreg);
frbc_status BGBCC_FrBC_PeekURegister(BGBCC_FrCC_State *ctx,frbc_register *rreg);
frbc_status BGBCC_FrBC_PushMark(BGBCC_FrCC_State *ctx);
int BGBCC_FrBC_LookupArgIndex(BGBCC_FrCC_State *ctx, char *name);
int BGBCC_FrBC_LookupLocalIndex(BGBCC_FrCC_State *ctx, char *name);
int BGBCC_FrBC_LookupGlobalIndex(BGBCC_FrCC_State *ctx, char *name);
int BGBCC_FrBC_LookupAsRegister(BGBCC_FrCC_State *ctx,char *name, frbc_register *rreg);
BGBCC_FrCC_RegisterInfo *BGBCC_FrBC_LookupLocalInfo(BGBCC_FrCC_State *ctx, char *name);
BGBCC_FrCC_RegisterInfo *BGBCC_FrBC_LookupArgInfo(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_PushLoad(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_PopStore(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_StackTransforCallArgs(BGBCC_FrCC_State *ctx);
int BGBCC_FrBC_StackGetCntCallArgs(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackCallName(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_StackPopCall(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackLoadIndexConst(BGBCC_FrCC_State *ctx, int idx);
frbc_status BGBCC_FrBC_StackStoreIndexConst(BGBCC_FrCC_State *ctx, int idx);
frbc_status BGBCC_FrBC_StackLoadIndexAddrConst(BGBCC_FrCC_State *ctx, int idx);
frbc_status BGBCC_FrBC_StackLoadIndex(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackStoreIndex(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackLoadIndexAddr(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackDup(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackDupClean(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackRetV(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackRet(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackCastBool(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackCastSig(BGBCC_FrCC_State *ctx, char *sig);
frbc_status BGBCC_FrBC_StackBinaryOp(BGBCC_FrCC_State *ctx, char *op);
frbc_status BGBCC_FrBC_StackUnaryOp(BGBCC_FrCC_State *ctx, char *op);
frbc_status BGBCC_FrBC_StackPushConstInt(BGBCC_FrCC_State *ctx, s32 val);
frbc_status BGBCC_FrBC_StackPushConstLong(BGBCC_FrCC_State *ctx, s64 val);
frbc_status BGBCC_FrBC_StackPushConstFloat(BGBCC_FrCC_State *ctx, double val);
frbc_status BGBCC_FrBC_StackPushConstDouble(BGBCC_FrCC_State *ctx, double val);
frbc_status BGBCC_FrBC_StackPushConstString(BGBCC_FrCC_State *ctx, char *val);
frbc_status BGBCC_FrBC_StackPushConstWString(BGBCC_FrCC_State *ctx, char *val);
frbc_status BGBCC_FrBC_StackPop(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackLoadAddr(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_StackSizeofSig(BGBCC_FrCC_State *ctx, char *sig);
frbc_status BGBCC_FrBC_StackSizeofVal(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackOffsetof(BGBCC_FrCC_State *ctx,char *sig, char *name);
frbc_status BGBCC_FrBC_StackLoadSlot(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_StackStoreSlot(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_StackLoadSlotAddr(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_StackFn(BGBCC_FrCC_State *ctx, char *fn);
frbc_status BGBCC_FrBC_StackLn(BGBCC_FrCC_State *ctx, int ln);
frbc_status BGBCC_FrBC_StackBeginU(BGBCC_FrCC_State *ctx, char *sig);
frbc_status BGBCC_FrBC_StackEndU(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackSetU(BGBCC_FrCC_State *ctx);
frbc_status BGBCC_FrBC_StackInitVar(BGBCC_FrCC_State *ctx, char *name);
frbc_status BGBCC_FrBC_StackInitVarValue(BGBCC_FrCC_State *ctx, char *name);
//AHSRC:frcc/frbc_struct.c
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_LookupStructureForSig(BGBCC_FrCC_State *ctx, char *sig);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_LookupStructureForSig2(BGBCC_FrCC_State *ctx, char *sig);
int BGBCC_FrBC_LookupStructureIDForSig(BGBCC_FrCC_State *ctx, char *sig);
BGBCC_FrCC_LiteralInfo *BGBCC_FrBC_LookupStructureForType(BGBCC_FrCC_State *ctx, frbc_type type);
int BGBCC_FrBC_LookupStructFieldID(BGBCC_FrCC_State *ctx, BGBCC_FrCC_LiteralInfo *st, char *name);
frbc_status BGBCC_FrBC_LookupStructFieldType(BGBCC_FrCC_State *ctx, BGBCC_FrCC_LiteralInfo *st, char *name, frbc_type *rty);
frbc_status BGBCC_FrBC_EmitOffsetOf(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, BGBCC_FrCC_LiteralInfo *st, char *name);
frbc_status BGBCC_FrBC_EmitLoadSlot(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src, BGBCC_FrCC_LiteralInfo *st, char *name);
frbc_status BGBCC_FrBC_EmitStoreSlot(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src, BGBCC_FrCC_LiteralInfo *st, char *name);
frbc_status BGBCC_FrBC_EmitLoadSlotAddr(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, frbc_register src, BGBCC_FrCC_LiteralInfo *st, char *name);
frbc_status BGBCC_FrBC_EmitInitObj(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, BGBCC_FrCC_LiteralInfo *st);
int BGBCC_FrBC_GetArraySizeForSig(BGBCC_FrCC_State *ctx, char *sig);
int BGBCC_FrBC_GetArraySizeForSig2(BGBCC_FrCC_State *ctx, char *sig);
int BGBCC_FrBC_GetArraySizeForSig2R(BGBCC_FrCC_State *ctx, char **rsig);
frbc_status BGBCC_FrBC_EmitInitArr(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, int sz);
frbc_status BGBCC_FrBC_EmitInitObjArr(BGBCC_FrCC_State *ctx, frbc_type type, frbc_register dst, BGBCC_FrCC_LiteralInfo *st, int sz);
//AHSRC:frcc/frbc_type.c
bool BGBCC_FrBC_TypeSmallIntP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeSmallLongP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeUnsignedP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeIntP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeLongP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeUnsignedIntP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeUnsignedLongP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeFloatP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeDoubleP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeBaseILFD_P(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeBaseSmallILFD_P(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeBaseSmallILFDP_P(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeBaseSmallIL_P(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypePointerP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeArrayP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeSignedByteP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeUnsignedByteP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeSignedShortP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeUnsignedShortP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeVoidP(BGBCC_FrCC_State *ctx, frbc_type ty);
bool BGBCC_FrBC_TypeEqualP(BGBCC_FrCC_State *ctx, frbc_type dty, frbc_type sty);
bool BGBCC_FrBC_TypeBaseEqualP(BGBCC_FrCC_State *ctx, frbc_type dty, frbc_type sty);
bool BGBCC_FrBC_TypeOprBasicP(BGBCC_FrCC_State *ctx, frbc_type ty);
int BGBCC_FrBC_TypeAsOprBasic(BGBCC_FrCC_State *ctx, frbc_type ty);
frbc_status BGBCC_FrBC_TypeDerefType(BGBCC_FrCC_State *ctx, frbc_type sty, frbc_type *rdty);
frbc_status BGBCC_FrBC_TypePointerType(BGBCC_FrCC_State *ctx, frbc_type sty, frbc_type *rdty);
frbc_status BGBCC_FrBC_TypeAutoPromoteType(BGBCC_FrCC_State *ctx, frbc_type sty, frbc_type *rdty);
frbc_status BGBCC_FrBC_TypeFromSig(BGBCC_FrCC_State *ctx, frbc_type *rty, char *sig);
char *BGBCC_FrBC_TypeGetSig(BGBCC_FrCC_State *ctx, frbc_type ty);
frbc_type BGBCC_FrBC_TypeWrapBasicType(int ty);
int BGBCC_FrBC_GetTypeConvMode(BGBCC_FrCC_State *ctx, frbc_type dty, frbc_type sty);
int BGBCC_FrBC_GetTypeConvIMode(BGBCC_FrCC_State *ctx, frbc_type dty, frbc_type sty);
int BGBCC_FrBC_GetTypeConvLMode(BGBCC_FrCC_State *ctx, frbc_type dty, frbc_type sty);
int BGBCC_FrBC_GetTypeConvILMode(BGBCC_FrCC_State *ctx, frbc_type dty, frbc_type sty);
bool BGBCC_FrBC_TypeSupportsOperatorP(BGBCC_FrCC_State *ctx, frbc_type ty, int opr);
frbc_status BGBCC_FrBC_GetTypeBinaryDest(BGBCC_FrCC_State *ctx, int opr, frbc_type lty, frbc_type rty, frbc_type *rdty);
//AHSRC:frcc/frcc_bind.c
int BGBCC_FrCC_BindSig(BGBCC_FrCC_State *ctx, char *name, char *sig);
int BGBCC_FrCC_BindTypeSig(BGBCC_FrCC_State *ctx, char *name, char *sig);
int BGBCC_FrCC_BindVarSig(BGBCC_FrCC_State *ctx, char *name, char *sig);
int BGBCC_FrCC_BindVarInfo(BGBCC_FrCC_State *ctx, char *name, char *key, char *val);
int BGBCC_FrCC_BindTypeInfo(BGBCC_FrCC_State *ctx, char *name, char *key, char *val);
int BGBCC_FrCC_BindDyTypeSig(BGBCC_FrCC_State *ctx, char *name, char *sig);
int BGBCC_FrCC_BindStructSig(BGBCC_FrCC_State *ctx, char *name, char *sig);
int BGBCC_FrCC_BindStructInfo(BGBCC_FrCC_State *ctx,char *name, char *key, char *val);
int BGBCC_FrCC_BindStructInfoIdx(BGBCC_FrCC_State *ctx,char *name, char *key, int idx, char *val);
int BGBCC_FrCC_BindFieldSig(BGBCC_FrCC_State *ctx,char *cls, char *name, char *sig);
int BGBCC_FrCC_BindFieldInfo(BGBCC_FrCC_State *ctx,char *cls, char *name, char *key, char *val);
int BGBCC_FrCC_BindStructInfoI(BGBCC_FrCC_State *ctx,char *name, char *key, int val);
int BGBCC_FrCC_BindFieldInfoI(BGBCC_FrCC_State *ctx,char *cls, char *name, char *key, int val);
//AHSRC:frcc/frcc_compile.c
void BGBCC_FrCC_Warn(BGBCC_FrCC_State *ctx, char *str, ...);
void BGBCC_FrCC_Error(BGBCC_FrCC_State *ctx, char *str, ...);
void BGBCC_FrCC_Note(BGBCC_FrCC_State *ctx, char *str, ...);
void BGBCC_FrCC_StubErrorLLn(BGBCC_FrCC_State *ctx,char *file, int line);
char *BGBCC_FrCC_GenSym(BGBCC_FrCC_State *ctx);
char *BGBCC_FrCC_GenSym2(BGBCC_FrCC_State *ctx);
int BGBCC_FrCC_CompileSwitch(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileInitVar(BGBCC_FrCC_State *ctx,char *name, BCCX_Node *type, BCCX_Node *value);
void BGBCC_FrCC_CompileStatement(BGBCC_FrCC_State *ctx, BCCX_Node *l);
char *BGBCC_FrCC_VarTypeString_FlattenExpr(BGBCC_FrCC_State *ctx,char *dst, BCCX_Node *l, int fl);
char *BGBCC_FrCC_VarTypeString_FlattenName(BGBCC_FrCC_State *ctx,char *t, char *s, int fl);
int BGBCC_FrCC_VarTypeString_ModifierChar(BGBCC_FrCC_State *ctx, int i);
char *BGBCC_FrCC_VarTypeString_FlattenModifiers(BGBCC_FrCC_State *ctx,char *t, int fl);
char *BGBCC_FrCC_VarTypeString_FlattenModifiers2(BGBCC_FrCC_State *ctx,char *t, int fl);
char *BGBCC_FrCC_VarTypeString(BGBCC_FrCC_State *ctx, BCCX_Node *ty);
char *BGBCC_FrCC_VarImageTypeString(BGBCC_FrCC_State *ctx, BCCX_Node *ty);
char *BGBCC_FrCC_VarTypeFlagsString(BGBCC_FrCC_State *ctx, BCCX_Node *ty);
void BGBCC_FrCC_EmitVarFunc(BGBCC_FrCC_State *ctx,char *name, BCCX_Node *ty, BCCX_Node *args);
void BGBCC_FrCC_EmitVar(BGBCC_FrCC_State *ctx,char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_FrCC_EmitVar2(BGBCC_FrCC_State *ctx,char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_FrCC_EmitVar3(BGBCC_FrCC_State *ctx, char *name, char *ty);
void BGBCC_FrCC_EmitVarProperty(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileVarProperty(BGBCC_FrCC_State *ctx, BCCX_Node *l);
int BGBCC_FrCC_CompileVarDummyP(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileVarStatement(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileVarStatement2(BGBCC_FrCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_FrCC_CompileBlock(BGBCC_FrCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args, BCCX_Node *body);
char *BGBCC_FrCC_GenProtoSig(BGBCC_FrCC_State *ctx,BCCX_Node *type, BCCX_Node *args);
void BGBCC_FrCC_EmitSigProto(BGBCC_FrCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
char *BGBCC_FrCC_VarSigProto(BGBCC_FrCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
BCCX_Node *BGBCC_FrCC_CompileProto(BGBCC_FrCC_State *ctx,BCCX_Node *type, char *name, BCCX_Node *args);
void BGBCC_FrCC_CompileStruct(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileUnion(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileClass(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileEnum(BGBCC_FrCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_FrCC_CompileSProto(BGBCC_FrCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_FrCC_GetNodeAttribute(BGBCC_FrCC_State *ctx,BCCX_Node *l, char *name);
char *BGBCC_FrCC_GetNodeAttributeString(BGBCC_FrCC_State *ctx,BCCX_Node *l, char *name);
void BGBCC_FrCC_CompileTypedef(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileStructs(BGBCC_FrCC_State *ctx);
void BGBCC_FrCC_EmitVarValue(BGBCC_FrCC_State *ctx, BCCX_Node *v);
void BGBCC_FrCC_EmitVarValueR(BGBCC_FrCC_State *ctx, BCCX_Node *v);
void BGBCC_FrCC_EmitVarValueR2(BGBCC_FrCC_State *ctx, BCCX_Node *v);
char *BGBCC_FrCC_QualifyNameNS(BGBCC_FrCC_State *ctx, char *name);
void BGBCC_FrCC_EmitTopVar(BGBCC_FrCC_State *ctx,char *name, BCCX_Node *ty, BCCX_Node *v);
void BGBCC_FrCC_CompileTopStatement(BGBCC_FrCC_State *ctx, BCCX_Node *l);
int BGBCC_FrCC_CompileModuleCTX(BGBCC_FrCC_State *ctx, char *name, BCCX_Node *l);
char *BGBCC_FrCC_CompileModule(char *name, BCCX_Node *l);
//AHSRC:frcc/frcc_expr.c
char *BGBCC_FrCC_CIfy(char *s);
void BGBCC_FrCC_CompileAssign(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileExprList(BGBCC_FrCC_State *ctx, BCCX_Node *lst);
void BGBCC_FrCC_CompileExprListReverse(BGBCC_FrCC_State *ctx, BCCX_Node *lst);
void BGBCC_FrCC_CompileArgsList(BGBCC_FrCC_State *ctx, BCCX_Node *lst);
void BGBCC_FrCC_CompileFuncall(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileForm(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileExprT(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileExpr(BGBCC_FrCC_State *ctx, BCCX_Node *l);
void BGBCC_FrCC_CompileExprTail(BGBCC_FrCC_State *ctx, BCCX_Node *l);
//AHSRC:frcc/frcc_index.c
void BGBCC_FrCC_EmitLabel(BGBCC_FrCC_State *ctx, char *name);
void BGBCC_FrCC_CompileBreak(BGBCC_FrCC_State *ctx);
void BGBCC_FrCC_CompileContinue(BGBCC_FrCC_State *ctx);
void BGBCC_FrCC_CompileBreakFalse(BGBCC_FrCC_State *ctx);
void BGBCC_FrCC_CompileBreakTrue(BGBCC_FrCC_State *ctx);
void BGBCC_FrCC_CompileContinueFalse(BGBCC_FrCC_State *ctx);
void BGBCC_FrCC_CompileContinueTrue(BGBCC_FrCC_State *ctx);
void BGBCC_FrCC_CompileJmp(BGBCC_FrCC_State *ctx, char *s);
void BGBCC_FrCC_CompileJmpFalse(BGBCC_FrCC_State *ctx, char *s);
void BGBCC_FrCC_CompileJmpTrue(BGBCC_FrCC_State *ctx, char *s);
void BGBCC_FrCC_CompileJmpCond(BGBCC_FrCC_State *ctx, char *op, char *s);
void BGBCC_FrCC_CompileJCO(BGBCC_FrCC_State *ctx, char *op,BCCX_Node *ln, BCCX_Node *rn, char *s);
void BGBCC_FrCC_CompileJCT(BGBCC_FrCC_State *ctx, BCCX_Node *l, char *s);
void BGBCC_FrCC_CompileJCF(BGBCC_FrCC_State *ctx, BCCX_Node *l, char *s);
int BGBCC_FrCC_TryGetSizeofType(BGBCC_FrCC_State *ctx, BCCX_Node *ty);
//AHSRC:frcc/frcc_reduce.c
int BGBCC_FrCC_IsUnaryP(BGBCC_FrCC_State *ctx, BCCX_Node *l, char *op);
int BGBCC_FrCC_IsBinaryP(BGBCC_FrCC_State *ctx, BCCX_Node *l, char *op);
int BGBCC_FrCC_BoolExpr(BGBCC_FrCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_FrCC_WrapIntSuf(s64 i, char *suf);
BCCX_Node *BGBCC_FrCC_WrapRealSuf(double f, char *suf);
BCCX_Node *BGBCC_FrCC_WrapInt(s64 i);
BCCX_Node *BGBCC_FrCC_WrapReal(double f);
int BGBCC_FrCC_IsIntP(BGBCC_FrCC_State *ctx, BCCX_Node *l);
int BGBCC_FrCC_IsRealP(BGBCC_FrCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_FrCC_Boolify(BGBCC_FrCC_State *ctx, BCCX_Node *l);
char *BGBCC_FrCC_BinaryTySuf(BGBCC_FrCC_State *ctx, char *op,BCCX_Node *ln, BCCX_Node *rn);
BCCX_Node *BGBCC_FrCC_ReduceForm(BGBCC_FrCC_State *ctx, BCCX_Node *l);
int BGBCC_FrCC_SetLine(BGBCC_FrCC_State *ctx, BCCX_Node *l,char *fn, int ln);
BCCX_Node *BGBCC_FrCC_ReduceStatementForm(BGBCC_FrCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_FrCC_ReduceExpr(BGBCC_FrCC_State *ctx, BCCX_Node *l);
BCCX_Node *BGBCC_FrCC_ReduceStatement(BGBCC_FrCC_State *ctx, BCCX_Node *l);
//AHSRC:mm/cc_tokord.c
//AHSRC:mm/ccx_node.c
BCCX_Attr *BCCX_LookupAttr(BCCX_Node *n, char *var);
BCCX_Attr *BCCX_LookupAttrNS(BCCX_Node *n, char *ns, char *var);
BCCX_Attr *BCCX_NewAttr();
BCCX_Attr *BCCX_FetchAttr(BCCX_Node *n, char *var);
BCCX_Attr *BCCX_FetchAttrNS(BCCX_Node *n, char *ns, char *var);
char *BCCX_Get(BCCX_Node *n, char *var);
char *BCCX_Get_SI(BCCX_Node *n, char *var);
int BCCX_GetInt(BCCX_Node *n, char *var);
double BCCX_GetFloat(BCCX_Node *n, char *var);
char *BCCX_GetNS(BCCX_Node *n, char *ns, char *var);
int BCCX_GetIntNS(BCCX_Node *n, char *ns, char *var);
double BCCX_GetFloatNS(BCCX_Node *n, char *ns, char *var);
void BCCX_Set(BCCX_Node *n, char *var, char *val);
void BCCX_SetInt(BCCX_Node *n, char *var, int val);
void BCCX_SetFloat(BCCX_Node *n, char *var, double val);
void BCCX_SetNS(BCCX_Node *n, char *ns, char *var, char *val);
void BCCX_SetIntNS(BCCX_Node *n, char *ns, char *var, int val);
void BCCX_SetFloatNS(BCCX_Node *n, char *ns, char *var, double val);
char *BCCX_NSURI(BCCX_Node *n, char *ns);
char *BCCX_URINS(BCCX_Node *n, char *uri);
char *BCCX_GetURI(BCCX_Node *n, char *uri, char *var);
int BCCX_GetIntURI(BCCX_Node *n, char *uri, char *var);
double BCCX_GetFloatURI(BCCX_Node *n, char *uri, char *var);
void BCCX_SetURI(BCCX_Node *n, char *uri, char *var, char *val);
void BCCX_SetIntURI(BCCX_Node *n, char *uri, char *var, int val);
void BCCX_SetFloatURI(BCCX_Node *n, char *uri, char *var, double val);
BCCX_Node *BCCX_New(char *tag);
BCCX_Node *BCCX_NewNS(char *ns, char *tag);
BCCX_Node *BCCX_NewText(char *text);
void BCCX_Add(BCCX_Node *parent, BCCX_Node *child);
BCCX_Node *BCCX_AddEnd(BCCX_Node *lst, BCCX_Node *n);
BCCX_Node *BCCX_AddEnd2(BCCX_Node *fst, BCCX_Node **rlst, BCCX_Node *n);
BCCX_Node *BCCX_New1(char *tag, BCCX_Node *a);
BCCX_Node *BCCX_New2(char *tag, BCCX_Node *a, BCCX_Node *b);
BCCX_Node *BCCX_New3(char *tag, BCCX_Node *a, BCCX_Node *b, BCCX_Node *c);
BCCX_Node *BCCX_New4(char *tag, BCCX_Node *a, BCCX_Node *b, BCCX_Node *c, BCCX_Node *d);
BCCX_Node *BCCX_New1NS(char *ns, char *tag, BCCX_Node *a);
BCCX_Node *BCCX_New2NS(char *ns, char *tag, BCCX_Node *a, BCCX_Node *b);
BCCX_Node *BCCX_New3NS(char *ns, char *tag, BCCX_Node *a, BCCX_Node *b, BCCX_Node *c);
BCCX_Node *BCCX_New4NS(char *ns, char *tag,BCCX_Node *a, BCCX_Node *b, BCCX_Node *c, BCCX_Node *d);
int BCCX_NodeP(BCCX_Node *n);
int BCCX_TextP(BCCX_Node *n);
int BCCX_LeafP(BCCX_Node *n);
int BCCX_ChildP(BCCX_Node *n);
BCCX_Node *BCCX_Next(BCCX_Node *n);
BCCX_Node *BCCX_Prev(BCCX_Node *n);
BCCX_Node *BCCX_Parent(BCCX_Node *n);
BCCX_Node *BCCX_Child(BCCX_Node *n);
char *BCCX_NS(BCCX_Node *n);
char *BCCX_URI(BCCX_Node *n);
char *BCCX_Tag(BCCX_Node *n);
char *BCCX_Text(BCCX_Node *n);
void BCCX_SetTag(BCCX_Node *n, char *s);
int BCCX_TagIsP(BCCX_Node *n, char *str);
int BCCX_AttrIsP(BCCX_Node *n, char *var, char *val);
int BCCX_TagAttrIsP(BCCX_Node *n, char *tag, char *var, char *val);
BCCX_Node *BCCX_FindNextTag(BCCX_Node *last, char *tag);
BCCX_Node *BCCX_FindNextAttr(BCCX_Node *last, char *var, char *val);
BCCX_Node *BCCX_FindNextTagAttr(BCCX_Node *last,char *tag, char *var, char *val);
BCCX_Node *BCCX_FindTag(BCCX_Node *parent, char *tag);
BCCX_Node *BCCX_FindAttr(BCCX_Node *parent, char *var, char *val);
BCCX_Node *BCCX_FindTagAttr(BCCX_Node *parent, char *tag, char *var, char *val);
BCCX_Node *BCCX_Fetch(BCCX_Node *parent, char *tag);
BCCX_Node *BCCX_Clone(BCCX_Node *n);
BCCX_Node *BCCX_CloneList(BCCX_Node *n);
void BCCX_Unlink(BCCX_Node *n);
//AHSRC:mm/ccx_print.c
char *BCCX_PrintText(char *s, char *t);
void BCCX_PrintBufSpecial(BCCX_Node *node, int ind,void (*pb)(void *p, char *b), void *ob);
void BCCX_PrintBuf(BCCX_Node *node, int ind,void (*pb)(void *p, char *b), void *ob);
void BCCX_DumpFD(FILE *fd, BCCX_Node *node);
void BCCX_PrintFD(FILE *fd, BCCX_Node *node);
char *BCCX_DumpStr(char *buf, BCCX_Node *node);
char *BCCX_PrintStr(char *buf, BCCX_Node *node);
void BCCX_Print(BCCX_Node *node);
//AHSRC:mm/ccx_parse.c
BCCX_ReadStream BCCX_NewReadStreamBuf(char *buf);
BCCX_ReadPos BCCX_GetPos(BCCX_ReadStream strm);
void BCCX_SetPos(BCCX_ReadStream strm, BCCX_ReadPos pos);
int BCCX_PeekChar(BCCX_ReadStream strm);
int BCCX_ReadChar(BCCX_ReadStream strm);
int BCCX_PeekCharIdx(BCCX_ReadStream strm, int idx);
int BCCX_ParseEatWhite(BCCX_ReadStream strm);
int BCCX_ParseSpecialP(BCCX_ReadStream strm);
int BCCX_ParseContSpecialP(BCCX_ReadStream strm);
char *BCCX_ParseToken(BCCX_ReadStream strm, int *ty);
char *BCCX_PeekToken(BCCX_ReadStream strm, int *ty);
char *BCCX_ParseText(BCCX_ReadStream strm);
BCCX_Attr *BCCX_ParseOpts(BCCX_ReadStream strm);
BCCX_Node *BCCX_ParseTag(BCCX_ReadStream strm, int *rgrp);
BCCX_Node *BCCX_ParseExprR(BCCX_ReadStream strm, int *rgrp);
BCCX_Node *BCCX_ParseExpr(BCCX_ReadStream strm);
BCCX_Node *BCCX_ParseExprStr(char *str);
//AHSRC:mm/ccx_sbxe.c
void *sbxe_malloc(int sz);
void *sbxe_tmalloc(char *ty, int sz);
void sbxe_free(void *ptr);
int SBXE_WriteNodeList(byte *buf, BCCX_Node *expr);
BCCX_Node *SBXE_ReadNodeList(byte *buf);
//AHSRC:mm/cc_float16.c
u32 BGBCC_Float16_ConvertMantissa(u32 i);
BGBCC_API int BGBCC_Float16_Init();
BGBCC_API double BGBCC_DecodeFloat16(u16 val);
BGBCC_API u16 BGBCC_EncodeFloat16(double val);
BGBCC_API double BGBCC_DecodeFloat16F(u16 val);
BGBCC_API double BGBCC_DecodeFloat12(u16 val);
BGBCC_API u16 BGBCC_EncodeFloat12(double val);
BGBCC_API u16 BGBCC_NegFloat16(u16 x);
BGBCC_API u16 BGBCC_RcpFloat16(u16 x);
BGBCC_API u16 BGBCC_SqrtFloat16(u16 x);
BGBCC_API u16 BGBCC_AddFloat16(u16 x, u16 y);
BGBCC_API u16 BGBCC_AddFloat16F(u16 x, u16 y);
BGBCC_API u16 BGBCC_AddFloat16F(u16 x, u16 y);
BGBCC_API u16 BGBCC_SubFloat16(u16 x, u16 y);
BGBCC_API u16 BGBCC_MulFloat16(u16 x, u16 y);
BGBCC_API u16 BGBCC_MulFloat16F(u16 x, u16 y);
BGBCC_API u32 BGBCC_MulFloat16F2P(u32 x, u32 y);
BGBCC_API u64 BGBCC_MulFloat16F4P(u64 x, u64 y);
BGBCC_API u16 BGBCC_DivFloat16(u16 x, u16 y);
//AHSRC:mm/cc_malloc.c
void BGBCC_DieError();
void BGBCC_DieFatal();
void BGBCC_CleanupAll();
void *bgbcc_tmalloc(char *ty, int sz);
void *bgbcc_malloc(int sz);
void *bgbcc_tmalloc2(char *ty, int sz);
void *bgbcc_malloc2(int sz);
void bgbcc_free(void *p);
void *bgbcc_realloc(void *ptr, int sz);
char *bgbcc_strdup(char *str);
int bgbcc_strdup_i(char *str);
char *bgbcc_strtab_i(int i);
char *bgbcc_strdup(char *str);
void *bgbcc_ralloc(int sz);
char *bgbcc_rstrdup(char *s);
char **bgbcc_split(char *s);
char *bgbcc_rstradd(char *s0, char *s1);
char *bgbcc_rstradd2(char *s0, char *s1, char *s2);
char *bgbcc_rstradd3(char *s0, char *s1, char *s2, char *s3);
void *bgbcc_neword(char **tab);
int bgbcc_strord(char *str, void *tab);
int BGBCC_GetOrdinal(char *str);
int BGBCC_CheckOrdinalFlag(int i, int ty);
int BGBCC_GetOrdinalLang(char *str, int lang);
int BGBCC_GetOrdinalLangType(char *str, int lang, int ty);
double BGBCC_ParseNumber(char *str);
//AHSRC:cc_api.c
void BCCX_DumpVF(void *fd, BCCX_Node *node);
void BCCX_PrintVF(void *fd, BCCX_Node *node);
int BGBCC_BindSig(BGBCC_State *ctx, char *name, char *sig);
int BGBCC_BindTypeSig(BGBCC_State *ctx, char *name, char *sig);
int BGBCC_BindVarSig(BGBCC_State *ctx, char *name, char *sig);
int BGBCC_BindVarInfo(BGBCC_State *ctx, char *name, char *key, char *val);
int BGBCC_BindTypeInfo(BGBCC_State *ctx, char *name, char *key, char *val);
int BGBCC_BindDyTypeSig(BGBCC_State *ctx, char *name, char *sig);
char *BGBCP_LookupSig(BGBCP_ParseState *ctx, char *name);
char *BGBCP_LookupTypeSig(BGBCP_ParseState *ctx, char *name);
int BGBCC_BindStructSig(BGBCC_State *ctx, char *name, char *sig);
int BGBCC_BindStructInfo(BGBCC_State *ctx, char *name, char *key, char *val);
int BGBCC_BindStructInfoIdx(BGBCC_State *ctx,char *name, char *key, int idx, char *val);
int BGBCC_BindFieldSig(BGBCC_State *ctx, char *cls, char *name, char *sig);
int BGBCC_BindFieldInfo(BGBCC_State *ctx,char *cls, char *name, char *key, char *val);
int BGBCC_BindStructInfoI(BGBCC_State *ctx,char *name, char *key, int val);
int BGBCC_BindFieldInfoI(BGBCC_State *ctx,char *cls, char *name, char *key, int val);
char *BGBCP_LookupPPKey(BGBCP_ParseState *ctx, char *name);
int BGBCC_BindPPKey(BGBCP_ParseState *ctx, char *name, char *sig);
int BGBCC_StoreTextFile(char *name, char *buf);
int BGBCC_StoreFile(char *name, void *buf, int sz);
int BGBCC_GetArch();
char *bgbcc_loadfile(char *name, int *rsz);
char *BGBCC_ReadFile(char *name, int *rsz);
int BGBCC_LoadCSourceBuffer(char *name, char *buf);
int BGBCC_LoadCSource(char *name, char *out);
int BGBCC_LoadCHeader(char *name);
int BGBCC_LoadLibrary(char *name);
int BGBCC_LoadLibrary2(char *name);
int BGBCC_LoadLibraryGeneric(char *name);
int BGBCC_LoadModule(char *name);
int BGBCC_LoadModuleMulti(char *name, char **arg);
int BGBCC_CompileFile(char *name, char *out);
int BGBCC_LoadCompileScript(char *name);
BCCX_Node *BGBCC_LoadCSourceGast(char *name);
int BGBCC_LoadCSourceGastSBXE(char *name, byte *obuf, int *rsz);
int BGBCC_LoadCSourceBSVM(char *name);
int BGBCC_LoadModuleBSVM(char *name);
BCCX_Node *BGBCC_LoadCSourceAST(char *name);
int BGBCC_LoadCSourceFRBC(char *name, byte *obuf, int *rsz);
int BGBCC_InitEnv(int argc, char **argv, char **env);
int BGBCC_Init();
int BGBCC_InitEnv(int argc, char **argv, char **env);
int BGBCC_Init();
BGBCC_API void ccBindKey(char *key, char *val);
BGBCC_API char *ccLookupKey(char *key);
BGBCC_API void ccAddInclude(char *path);
BGBCC_API void ccAddLibrary(char *path);
BGBCC_API void ccAddSource(char *path);
void ccAddDefineString(char *str);
BGBCC_API int ccLoadModule(char *file);
BGBCC_API int ccLoadModuleMulti(char *name, char **args);
BGBCC_API int ccCompileModule(char *file, char *out);
BGBCC_API int ccLoadLibrary(char *name);
BGBCC_API int ccPrecompileModule(char *file);
BGBCC_API int ccLoadCompilerScript(char *file);
BGBCC_API int ccLoadModuleBSVM(char *file);
BGBCC_API int ccSubmitCSource(char *name, char *buf);
BGBCC_API void *ccGetAddr(char *sym);
BGBCC_API void ccSetAddr(char *sym, void *ptr);
BGBCC_API void *ccGetPtr(char *sym);
BGBCC_API void ccSetPtr(char *sym, void *v);
BGBCC_API int ccGetInt(char *sym);
BGBCC_API void ccSetInt(char *sym, int v);
BGBCC_API s64 ccGetLongLong(char *sym);
BGBCC_API void ccSetLongLong(char *sym, s64 v);
BGBCC_API float ccGetFloat(char *sym);
BGBCC_API void ccSetFloat(char *sym, float v);
BGBCC_API double ccGetDouble(char *sym);
BGBCC_API void ccSetDouble(char *sym, double v);
//AHSRC:cc_cache.c
void BGBCC_LoadCache();
void BGBCC_StoreCache();
int BGBCC_CacheAllocNode();
int BGBCC_CacheLookupFile(char *name);
int BGBCC_CacheGetFile(char *name);
int BGBCC_CacheCheckDepNodes(int node);
int BGBCC_CacheUpdateDepNodes(int node);
int BGBCC_CacheCheckFile(char *name);
int BGBCC_UpdateCheckFile(char *name);
