package bsvm.io;

public class InputStreamReader extends Reader
{
public InputStreamReader(InputStream is)
	{ }
public InputStreamReader(InputStream is, String enc)
	{ }

public void close()
	{ }
public void mark(int limit)
	{ }
public boolean markSupported()
	{ return false; }

public int read()
	{ return 0; }
public int read(char[] cbuf, int off, int len)
	{ return 0; }
public boolean ready()
	{ return false; }
public void reset()
	{ }
public long skip(long n)
	{ return 0; }
}
