package bsvm.io;

public abstract class InputStream extends Object
{

public InputStream()
	{}

public int available()
	{ return 0; }
public void close()
	{}
public void mark(int readlimit)
	{}
public boolean markSupported()
	{ return false; }

public abstract int read();

public int read(byte[] b)
	{ return 0; }
public int read(byte[] b, int off, int len)
	{ return 0; }
public void reset()
	{}
public long skip(long n)
	{ return 0; }

}
