//btac_util.c
BTAC_API void *bgbtac_ralloc(int sz);
BTAC_API char **bgbtac_split(char *s);
BTAC_API char *bgbtac_rstrdup(char *s);
BTAC_API char *bgbtac_strdup(char *s);
BTAC_API char *bgbtac_strdup(char *str);
BTAC_API void bgbtac_file_init();
BTAC_API void *bgbtac_fopen(char *name, char *mode);
BTAC_API void bgbtac_fclose(void *fd);
BTAC_API int bgbtac_fread(void *buf, int i, int j, void *fd);
BTAC_API int bgbtac_fwrite(void *buf, int i, int j, void *fd);
BTAC_API void bgbtac_fseek(void *buf, int i, int j);
BTAC_API int bgbtac_fgetc(void *fd);
BTAC_API int bgbtac_fputc(int i, void *fd);
BTAC_API int bgbtac_ftell(void *fd);
BTAC_API int bgbtac_feof(void *fd);
BTAC_API int bgbtac_fgets(void *buf, int sz, void *fd);
//btac_wave.c
BTAC_API int BGBTAC_ScaleSample(short *d, int dl, short *s, int sl);
BTAC_API byte *BGBTAC_LoadWAV(char *name, int *rch, int *rr, int *rbits, int *rlen);
BTAC_API void BGBTAC_StoreWAV(char *name, byte *buf, int ch, int rt, int bits, int len);
BTAC_API short *BGBTAC_LoadWAV16(char *name, int *rch, int *rrt, int *rlen);
BTAC_API short *BGBTAC_LoadWAV_Mono16(char *name, int *rrt, int *rlen);
BTAC_API short *BGBTAC_LoadWAV_44Mono16(char *name, int *rlen);
BTAC_API short *BGBTAC_LoadWAV_16Mono16(char *name, int *rlen);
BTAC_API short *BGBTAC_LoadWAV_Stereo16(char *name, int *rrt, int *rlen);
BTAC_API short *BGBTAC_LoadWAV_44Stereo16(char *name, int *rlen);
BTAC_API int BGBTAC_NormalizeSample(short *dst, short *src, int len);
BTAC_API double BGBTAC_SplinePolate(short *samp, int len, double t);
BTAC_API double BGBTAC_SplinePolateF(float *samp, int len, double t);
BTAC_API int BGBTAC_ScaleSampleTrilinear(short *d, int dl, short *s, int sl);
BTAC_API double BGBTAC_Sinc(double x);
BTAC_API double BGBTAC_SincPolate(short *samp, int len, double f, int n);
BTAC_API int BGBTAC_ScaleSampleSinc(short *d, int dl, short *s, int sl);
BTAC_API double BGBTAC_SplinePolate(short *samp, int len, double t);
BTAC_API double BGBTAC_SplinePolateF(float *samp, int len, double t);
BTAC_API double BGBTAC_SplinePolateLoop(short *samp, int len, double t);
BTAC_API int BGBTAC_ScaleSampleSpline(short *d, int dl, short *s, int sl);
BTAC_API int BGBTAC_ScaleSample(short *d, int dl, short *s, int sl);
BTAC_API int BGBTAC_ScaleSampleHQ(short *d, int dl, short *s, int sl);
BTAC_API int BGBTAC_SampleCompressor(short *db, int dl, short *sb, int sl,int ivl, int isl, int irl);
//btac_filter.c
void *bgbtac_malloc(int sz);
void bgbtac_free(void *ptr);
void BGBTAC_EncodeBlockStereoS16(s16 *iblk, byte *oblk);
BTAC_API void BGBTAC_EncodeStreamStereoS16(s16 *iblk, byte *oblk, int cnt);
void BGBTAC_EncodeBlockMonoS16(s16 *iblk, byte *oblk);
BTAC_API void BGBTAC_EncodeStreamMonoS16(s16 *iblk, byte *oblk, int len);
void BGBTAC_DecodeBlockMonoS16(byte *iblk, s16 *oblk);
BTAC_API void BGBTAC_DecodeStreamMonoS16(byte *iblk, s16 *oblk, int len);
void BGBTAC_EncodeBlock2MonoS16(s16 *iblk, byte *oblk);
void BGBTAC_DecodeBlock2MonoS16(byte *iblk, s16 *oblk);
BTAC_API void BGBTAC_EncodeStream2MonoS16(s16 *iblk, byte *oblk, int len);
BTAC_API void BGBTAC_DecodeStream2MonoS16(byte *iblk, s16 *oblk, int len);
//btac_filter2.c
void BGBTAC_EncodeBlock3MonoS16(s16 *iblk, byte *oblk);
BTAC_API void BGBTAC_EncodeStream3MonoS16(s16 *iblk, byte *oblk, int len);
void BGBTAC_DecodeBlock3MonoS16(byte *iblk, s16 *oblk);
BTAC_API void BGBTAC_DecodeStream3MonoS16(byte *iblk, s16 *oblk, int len);
void BGBTAC_EncodeBlock4MonoS16(s16 *iblk, byte *oblk);
void BGBTAC_DecodeBlock4MonoS16(byte *iblk, s16 *oblk);
BTAC_API void BGBTAC_EncodeStream4MonoS16(s16 *iblk, byte *oblk, int len);
BTAC_API void BGBTAC_DecodeStream4MonoS16(byte *iblk, s16 *oblk, int len);
//btac_filter3.c
int bgbtac_ssqrti(int v);
int bgbtac_ssqri(int v);
int bgbtac_spowi(int v, float e);
double bgbtac_ssqrt(double v);
double bgbtac_ssqr(double v);
void BGBTAC_EncodeBlockHeaderS16(s16 *iblk, byte *oblk, s16 *tcblk, int *rcm, int *rcn, int flags);
void BGBTAC_EncodeBlockHeaderS16(s16 *iblk, byte *oblk, s16 *tcblk, int *rcm, int *rcn, int flags);
void BGBTAC_EncodeBlockHeaderPanS16(s16 *iblk, byte *oblk, s16 *tcblk, s16 *tcpan, int *rcm, int *rcn, int *rlm, int *rln, int *rrm, int *rrn, int flags);
void BGBTAC_EncodeBlockHeaderSideS16(s16 *iblk, byte *oblk, s16 *tcblk, s16 *tcpan, int *rcm, int *rcn, int *rsm, int *rsn, int flags);
void BGBTAC_DecodeBlockHeader(byte *iblk, int flags,int *rcm, int *rcn, int *rca, int *rlm, int *rln, int *rla, int *rrm, int *rrn, int *rra);
void BGBTAC_DecodeBlockSideHeader(byte *iblk, int flags,int *rcm, int *rcn, int *rca, int *rsm, int *rsn, int *rsa);
void BGBTAC_EncodeBlock8S16(s16 *iblk, byte *oblk, int flags);
void BGBTAC_DecodeBlock8S16(byte *iblk, s16 *oblk, int flags);
void BGBTAC_EncodeBlock9S16(s16 *iblk, byte *oblk, int flags);
void BGBTAC_DecodeBlock9S16(byte *iblk, s16 *oblk, int flags);
void BGBTAC_EncodeBlock10S16(s16 *iblk, byte *oblk, int flags);
void BGBTAC_DecodeBlock10S16(byte *iblk, s16 *oblk, int flags);
void BGBTAC_EncodeBlock12S16(s16 *iblk, byte *oblk, int flags);
void BGBTAC_DecodeBlock12S16(byte *iblk, s16 *oblk, int flags);
void BGBTAC_EncodeBlock13S16(s16 *iblk, byte *oblk, int flags);
void BGBTAC_DecodeBlock13S16(byte *iblk, s16 *oblk, int flags);
void BGBTAC_EncodeBlock11S16(s16 *iblk, byte *oblk, int flags);
void BGBTAC_DecodeBlock11S16(byte *iblk, s16 *oblk, int flags);
void BGBTAC_EncodeBlock14S16(s16 *iblk, byte *oblk, int flags);
void BGBTAC_DecodeBlock14S16(byte *iblk, s16 *oblk, int flags);
BTAC_API void BGBTAC_FilterStreamMonoS16(s16 *buf, int len);
BTAC_API void BGBTAC_DeblockStreamMonoS16(s16 *oblk, int len);
BTAC_API void BGBTAC_FilterStreamS16(s16 *buf, int len);
BTAC_API void BGBTAC_DeblockStreamS16(s16 *oblk, int len);
void BGBTAC_EncodeBlockTagS16(s16 *iblk, byte *oblk,int tag, int flags);
void BGBTAC_DecodeBlockTagS16(byte *iblk, s16 *oblk, int flags);
void BGBTAC_CompandBlockS16(s16 *iblk, s16 *oblk, int flags);
void BGBTAC_UnCompandBlockS16(s16 *iblk, s16 *oblk, int flags);
BTAC_API int BGBTAC_CalcBlockErrorS16(s16 *iblk, s16 *tblk, int flags);
BTAC_API int BGBTAC_CheckBlockBestS16(s16 *iblk, int flags);
BTAC_API void BGBTAC_EncodeStreamS16(s16 *iblk, byte *oblk, int len, int flags);
BTAC_API void BGBTAC_DecodeStreamS16(byte *iblk, s16 *oblk, int len, int flags);
//btac_sample.c
BTAC_API BTAC_SampleHeader *BTAC_CreateSample(int chan, int rate, int bits, int len, int flags);
BTAC_API int BTAC_FlattenSample(BTAC_SampleHeader *head, byte *obuf, int osz);
BTAC_API int BTAC_SizeFlattenSample(BTAC_SampleHeader *head);
BTAC_API int BTAC_StoreSample(char *name, BTAC_SampleHeader *head);
BTAC_API BTAC_SampleHeader *BTAC_LoadSample(char *name);
