BUILD=.
DLLPF=lib

CC=$(TARG)-gcc
CC_OUTEXE=$(CC) -o 
CC_OUTDLL=$(CC) -shared -o 
CC_OUTOBJ=$(CC) -c -o 
CC_OUTTOOL=gcc -o 

CFLAGS=-Iinclude -I../include -g
DLL_CFLAGS=$(CFLAGS) -DBGBDY_DLL
LDFLAGS=-g -L. -lbgbdy -L.. -lbgbgc -lbgbdy -lbgbasm -lzpack -lm \
	-Wl,-rpath,"$$ORIGIN"
DLL_LDFLAGS=-L.. -lbgbgc -lbgbasm -lzpack -lm -fPIC \
	-Wl,-rpath,"$$ORIGIN"

include Makefile.inc

