BUILD=.
MKSUF=.msvc
LIBSUF=.lib
DLLSUF=.dll
EXESUF=.exe
OBJSUF=.obj
BINSUF=.exe
DLLPF=

CC_OUTEXE=cl /Fe
CC_OUTDLL=cl /LD /Fe
CC_OUTOBJ=cl /c /Fo
CC_OUTTOOL=cl /Fe

# CFLAGS=/Iinclude /I../include /Z7
CFLAGS=/Iinclude /I../include /Z7 /arch:SSE2
DLL_CFLAGS=$(CFLAGS) /DBGBDY_DLL
LDFLAGS=bgbdy.lib ../bgbgc.lib ../bgbasm.lib ../zpack.lib
DLL_LDFLAGS=../bgbgc.lib ../bgbasm.lib ../zpack.lib

include Makefile.inc

